### ISSUE TITLE
How to force the server disconnect disconnecting a client after responding?

### ISSUE THREAD

**Issue by pboettch** [eidheim/Simple-Web-Server#106]
It seems in HTTP/1.0 a connection was closed after a request was handled by the server.

And even in HTTP/1.1 if `Connection: close` header is set the server could close it right after responding. How can I do it with this library?

PS: Great stuff this library! Thanks.

**Comment by eidheim** [comment]
Thank you. If I'm not mistaken, the server will close the connection in both these cases. Have you checked?

**Comment by pboettch** [comment]
Sorry, I was of course not precise enough in my question, I'm talking about `SimpleWeb::Server<SimpleWeb::HTTP>` handling a HTTP 1.0 request. Here is my code:

```C++
#include <simple-web-server/server_http.hpp>

typedef SimpleWeb::Server<SimpleWeb::HTTP> HttpServer;

int main()
{
    HttpServer server;
    server.config.port = 8080;

    server.resource["^/$"]["GET"] =
        [](std::shared_ptr<HttpServer::Response> response,
           std::shared_ptr<HttpServer::Request>) {

            *response << "HTTP/1.0 200 OK\r\n"
                      << "\r\n"
                      << "text\r\n";
          };

    std::thread server_thread([&server]() {
        server.start();
    });

    std::this_thread::sleep_for(std::chrono::seconds(100));

    server.stop();
    server_thread.join();

    return EXIT_SUCCESS;
}
```

Using curl to fetch this stalls the until the curl-read-timeout triggers:

```
$ curl localhost:8080/ -v
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< 
text
//// here curl is waiting 2 seconds before closing.
* Curl_http_done: called premature == 0
* Closing connection 0
```

And curl is even telling me, that it expects the server to close after the data has been sent:
`* HTTP 1.0, assume close after body`

Now my question again, Is there a way to close the connection from my request-handler?

**Comment by eidheim** [comment]
You seem to be sending content without specifying Content-Length?

**Comment by pboettch** [comment]
Is this not allowed by the standard HTTP 1.0? I have a real webserver (on an embedded industrial thing) which is doing it like this.

**Comment by pboettch** [comment]
From [Key Differences between HTTP/1.0 and HTTP/1.1](http://www8.org/w8-papers/5c-protocols/key/key.html) 

- HTTP 1.0 does not require the `Content-Length`-header.
- HTTP/1.0, in its documented form, made no provision for persistent connections.

**Comment by eidheim** [comment]
This works: `curl localhost:8080 -0 -v`, that is when the request is HTTP/1.0. At the moment, the request decides when the connection should be closed. For backward compatibility it would be nice to support this HTTP1.0 feature, but I'm thinking that this is a highly special case and is solved by using Content-Length. I do not see an apparent way to add this feature either without adding unnecessary complexity to the server.

**Comment by pboettch** [comment]
In my case data is generated on the fly, it does not know how many bytes it will generate beforehand. And creating a stringstream to get the size would be too expensive.

Couldn't we tell the server via a method in the Response-object, to close the connection after returning from the handler?

**Comment by eidheim** [comment]
That is a possibility actually. Typically I guess one would use chunked transfer in your case, but that is requiring additional complexity as well.

**Comment by pboettch** [comment]
I tried something (see my PR), what do you think?

**Comment by eidheim** [comment]
Not sure why this did not get closed automatically, but the issue should be fixed in the above commit.
