### ISSUE TITLE
Issue with POST example,

### ISSUE THREAD

**Issue by fabianbuettner** [eidheim/Simple-Web-Server#111]
Hi,

The line server.resource["^/string$"]["POST"] from the http_examples.cpp does not seem to match for me using std::regex.
I am using curl to send a POST request like this: curl --form "fileupload=@start.sh" http://10.0.0.6/string
My gcc version: 4.8.1 and i am cross compiling for ARM.

regards,
Fabian Büttner

**Comment by pboettch** [comment]
Does it work in another environment? With a more recent GCC? 

As you might know, there is no support for `std::regex` in 4.8.x but Simple-Web-Server is using boost::regex if GCC's version is lower than 4.9.

Could you check whether the command line when compiling contains `-DUSE_BOOST_REGEX`?

How do you do the cross-compilation? With CMAKE_TOOLCHAIN_FILE?

**Comment by fabianbuettner** [comment]
I haven't tried it with a newer version of GCC, yet.

No, i didn't know that std::regex is not supported by gcc 4.8.x.
I just found out that the compiler is checked in the CMakeLists.txt.
I am using my custom CMakeLists.txt and copied server_http.hpp into my directory and wanted to try out one of your examples in my code base. That's the reason why i am compiling without -DUSE_BOOST_REGEX.

Yes i am using CMAKE_TOOLCHAIN_FILE.

**Comment by pboettch** [comment]
Well, to have regex work with gcc 4.8 you have to use `boost::regex` and enable it with defining `USE_BOOST_REGEX` for files which include `server_http.hpp`.

**Comment by fabianbuettner** [comment]
Thank you for your support!
I find it strange that i can compile the source although the compiler does not support std::regex.
This issue can be closed then.

**Comment by pboettch** [comment]
Does it work with the flag set?

For a discussion regarding std::regex and gcc 4.8 read the comment on the [StackOverflow Answer](http://stackoverflow.com/a/12665408/880584l)

**Comment by fabianbuettner** [comment]
Unfortunately, I currently don't have boost::regex compiled for my target platform that's why i made a workaround like this: `server.resource["/string"]["POST"]`

Thanks for the interesting link. At the moment, my workaround is good enough.

**Comment by fabianbuettner** [comment]
@pboettch It works with the flag set. Thanks.
