### ISSUE TITLE
How to send async request to server ?

### ISSUE THREAD

**Issue by pengweichu** [eidheim/Simple-Web-Server#114]
Hi, I will need use https client send the request to a server very frequently, therefore I need the async method to send request and receive response async in callback, does https client support ?

**Comment by eidheim** [comment]
The client is synchronous due to simplicity and its innate synchronous
nature. You can however place its request in a thread or thread pool of
your choice.

Ole

**Comment by jeffreyscottgraham** [comment]
I would like this feature added.

**Comment by eidheim** [comment]
After giving this some more thought, I'll most likely make the client request async during the summer. Have not yet decided if the current blocking request method should be deprecated or not.

**Comment by eidheim** [comment]
A first attempt can be seen at the above commit. I'll probably test this a week or two before pushing this commit to master. Feedback is welcome. 

The Client is now also more robust; reconnects and supports parallell requests on separate sockets if needed.
