### ISSUE TITLE
error in Tests build

### ISSUE THREAD

**Issue by amigo421** [eidheim/Simple-Web-Server#119]
just tried to build the tests and got the error:

> C:\dev\workspace\Simple-Web-Server\tests\parse_test.cpp(17): error C2248: 'SimpleWeb::ServerBase<SimpleWeb::HTTP>::Request::Request': cannot access private member declared in class 'SimpleWeb::ServerBase<SimpleWeb::HTTP>::Request'

**Comment by amigo421** [comment]
ah, I see the problem, this is GCC specific stuff, but I'm from vc world
I see cmakelists scripts are not adapted for other than GCC compilers

**Comment by eidheim** [comment]
I don't use Windows, but feel free to see if cl supports this option.

**Comment by amigo421** [comment]
as far as I know - no, it doesn't . will try to use your lib on Win for my project. on the moment, looks useful for me. thank you!

then I'm going to close the request.

just a question before that - I see a lot of boost libs used in your project currently included into the standard, or in TR, I mean : regex, chrono, thread, filesystem, asio can also be used without boost dependency. why you don't minimize the dependencies from other than standard libraries?

**Comment by amigo421** [comment]
please close the request, I currently don't know the solution, 
if will find this I'll raise a PR
