### ISSUE TITLE
Removing boost dependencies

### ISSUE THREAD

**Issue by sebt3** [eidheim/Simple-Web-Server#122]
Since boost can be a burdden (like on android), and since asio (http://think-async.com/Asio/) also exist without boost (being include-only library is even an added bonus). 
I've done a dirty work about this which seam to work as indented (not tested SSL yet) at my fork :
https://github.com/sebt3/Simple-Web-Server

I'm not issuing an PR since I'm guessing you would reject it :P

**Comment by sebt3** [comment]
Posting this issue, i was looking to talk to you on how to build a PR you would accept.
I would go in the same vein you did to support regex from boost and from STD. So I would suggest using :
- ASIO_NS to be either boost::asio or just asio (or boost:: or empty as you please)
- ERROR_NS to be either boost::system or std
- FS_NS to be used in the example
As boost also have a ::make_error_code my usage of it in std could be replicated using boost.
What do you think ?

I know current ASIO cannot be used with gcc 4.8, but it work for any version >=5. (I've yet to test 4.9). I havent checked clang yet (well I know clang 3.4 cannot compile with lastest ASIO). So this cannot be used with old compilers and boost will still be a requirement. This also mean the CMakeLists.txt will become even more important. It might be a good idea to provide an includable cmake file so we can cope with misusage.

BTW: SSL is now fully tested and working as expected

**Comment by eidheim** [comment]
I was thinking about the same, and it's probably doable with namespace and cmake tricks. I'll give it some more thought, but your initial idea here is great!

**Comment by eidheim** [comment]
Feel free to make a PR, and we can do the discussion there. Easier for me to test it and suggest changes then too.

**Comment by DraconPern** [comment]
Whatever you do, please don't make it dependent on cmake.  I use cmake with my projects and it has a very high barrier.  May be just use some ifdef test so that one can just include the cpp and .hpp files w/o cmake.

**Comment by eidheim** [comment]
@DraconPern I agree. At least the root CMakeLists.txt should be understandable so that it is possible, for those not experienced with cmake, to implement the same in another build management system. boost.asio will be made default for the time being (at least until 2020 I guess since std::asio did not make it to c++17), and standalone asio will be used if an appropriate preprocessor definition is set.

**Comment by sebt3** [comment]
I just fail to find time to work on this but I do agree too.

**Comment by sebt3** [comment]
This new PR do not depend on cmake, and boost keep being the default behaviour

**Comment by sebt3** [comment]
Use "-DUSE_STANDALONE_ASIO" to enable this.

Thanks again ;)
