### ISSUE TITLE
Increase QPS for persistent connection 

### ISSUE THREAD

**Issue by venediktov** [eidheim/Simple-Web-Server#123]
Tested your QPS seemed very low 17K QPS on persistent connection .
I used ab - Apache Venchmark with switch -k , it uses HTTP 1.0 keep-alive , so I had to add support to your code .
It went from 11k to 17K , but it's still way lower then my stack based on Boost.asio.

As a side note , your Händlers know too much of HTTP response .
I am not advocating you to change it overnight , but it would be nice to have something like boost proposed in its samples .

You are welocome to visit my project where I utilize 50K QPS CRUD handlers .
https://github.com/venediktov/vanilla-rtb

If you look at CRUD directory you will see http restful handsets that currently do 50K QPS on 4 core 2.2 GHz AMD ubuntu Linux .

Please let me know if you care about this issue , i don't insist you fix it , but I was looking at my performance lately and got to see your stack by accident .

Cheers ,
Vladimir .

**Comment by eidheim** [comment]
Which resource did you test against? The default resource in Simple-Web-Server includes file access and additionally is simplistically written to support large file downloads (for example purposes), which might greatly affect the result. Especially comparing to server resources that does not include file access.

**Comment by venediktov** [comment]
I tested against simple resource ,  restful handler, not file system
```
server.resource["^/string$"]["POST"]=[](shared_ptr<HttpServer::Response> response, shared_ptr<HttpServer::Request> request) {
        auto content=request->content.string();
        
        *response << "HTTP/1.0 200 OK\r\nConnection: keep-alive\r\nContent-Length: " << content.length() << "\r\n\r\n" << content;
};
```

I have tested it with apache benchmark aka ab .
I had to change HTTP to 1.0 and add keep-alive and I added line in your code to support keep-alive 
so it does not close connection when it gets in the header from ab  keep-alive instruction .


```
for(auto it=range.first;it!=range.second;it++) {
                            if(boost::iequals(it->second, "close")) {
                                return;
                            } else if (boost::iequals(it->second, "keep-alive")) {
                                this->read_request_and_content(response->socket);
                            }
                        }
```


If you add those changes and test with apache benchmark you can let me know what you get, I am getting 17K with persistent connection , but that's way below what Boost.asio can deliver .
I started adding benchmarks to my stack and you can maybe use google benchmark to identify the slow parts ? I am just trying to help .

**Comment by venediktov** [comment]
17000 requests per second

**Comment by eidheim** [comment]
Thank you, but it is quite lower than my own tests on Debian Testing as far as I remember. What g++ and boost versions do you have? That is, in case this would affect the results in some way. I'll look into this more next week. It might also help to know your Ubuntu version? And I take it you use g++ to compile, or do you use clang++ instead?

**Comment by venediktov** [comment]
Hi Christian,
I test both my stack and your stack on the same compiler gcc 5.4 , boost 1.61 , ubuntu 16.04 , both 
were built in Release mode , by default cmake creates -O3 optimization builds when you pass 
-DCMAKE_BUILD_TYPE=Release
I don't see much difference in how you used Boost.asio vs. how it was utilized in my stack, however there is one settle difference \:
-  use of shared_ptr ( those have impact in multi-threaded executions , it is used everywhere in your stack)
- request parser ( multiple pass ? )  - CRUD uses is a single pass parser
- async_read_until / async_read / stream_buf ( CRUD uses async_read_some only ) 

The rest seams fairly same as in CRUD . I can't tell you which piece made it slower then CRUD we
use in vanilla-rtb , we had request from a customer to pass through at least 50K QPS , initially it was
a problem for us too, now we fixed it.
Please let me know if you need more information from me.
Best,
Vladimir.

**Comment by eidheim** [comment]
When compiling with `-O3` I get around 63000 req/s using:
`httperf --server=localhost --port=8080 --uri=/match/123 --num-conns=200 --num-calls=1000`
Without `-O3` I get around 18600, so there is a large difference between release and normal build. 

With `-O3` and `ab -k -n 1000 -c 200 http://localhost:8080/match/123` I'm getting around 20000-25000 req/s. Not sure what is going on there. I applied your changes too, so it's not that. Might be some problem with the HTTP/1.0 keep alive-code I'm guessing, since httperf is using HTTP/1.1 by default. I'll look into it more when I got time. 

Tested on Intel® Core™ i7-2600 Processor (4 core, 3.40 GHz).

**Comment by eidheim** [comment]
Forgot to mention that the tests were run on Debian Testing with its default g++ (6.3.0).

**Comment by venediktov** [comment]
Hi Christian,
So your tests with ab ( 20-25K ) correlates with mine e.g. 17K on my 4 core 2.2Ghz.
There is a settle difference in httperf and ab \:
ab - stops sending request if it does not get responses
httperf - keeps sending requests even without getting response back

httperf is a good tool to stress test our stacks to see what happens when the load doubles, so I will probably add this tool to the suite of tools we use @venediktov/vanilla-rtb to tune up our stack.

One thing helped our team a lot was testing framework **google benchmarks**, you can see how vanilla-rtb project is utilizing it we have procided description in the README.md in benchmarks folder.

Thank you for your time in testing it out , we learn new things every day, that's what open-source community is good for.

Before I forget , if  in ab you use bigger number of requests -n 20000 you will get more stable results ( basically the QPS will not change much from one run to another ) , e.g.  will not show a big spread like 20K-25K.

Let me know how it goes,  in a meantime I will try out httperf with vanilla-rtb .
Thanks for sharing info.

Best,
Vlad.

**Comment by eidheim** [comment]
I tested some more, and with the following:
`ab -k -n 200000 -c 200 http://localhost:8080/match/123`
I constantly get around 63000 req/s. Not sure why I get higher req/s with higher number of requests with `ab` though.

@venediktov I'll also commit your Connection keep-alive (`server_http.hpp`) code to master if its ok with you. I'll then add you as author of course.

**Comment by venediktov** [comment]
Oh, then it's not an issue if you can get 63K QPS with more requests , on the fast machines I had to give more requests to ab , otherwise it can't calculate QPS correctly,  so the issue can be closed !

Yes,  it would be nice if your stack would support both 1.0 and 1.1 , you can add my name if you want of course .

Btw, If you are interested in technologies related to HTTP our stack depends heavily on HTTP protocol , but we also use UDP  and TCP/IP within our architecture for some models if/when our bidders read segmented ( unrelated ) data.
Currently we are assembling rapid-bidder based on vanilla-rtb stack , which should have complete cycle including bidding , win notifications, audit , campaign management and some management console .
Best,
Vladimir.

**Comment by eidheim** [comment]
I'll close this issue then, thank you Vladimir.
