### ISSUE TITLE
http examples

### ISSUE THREAD

**Issue by blackandwhitebg** [eidheim/Simple-Web-Server#126]
Hi there ...

A very small issue, it`s basically about source code consistency only.
I noticed that in http_examples.cpp Line 121 checks if the requested file exists, which looks like unreachable code, because the fact that "boost::filesystem::canonical" is used on line 114 instead of "boost::filesystem::weakly_canonical" guarantees that the file exists.

The same thing applies for the HTTPS example too.

**Comment by eidheim** [comment]
Thank you, I'll fix this soon.
