### ISSUE TITLE
Is it possible to integrate Simple-WebSocket-Server in order to use the same TCP port?

### ISSUE THREAD

**Issue by Shumen** [eidheim/Simple-Web-Server#13]
For example, there is only 80 TCP port available, which would provide html/css/javascript and RESTful service, as well as WebSocket service. Thank you!

**Comment by eidheim** [comment]
I guess in theory one could mix Simple-Web-Server and Simple-WebSocket-Server to achieve all in one port, but I would not recommend it, as it will be somewhat ugly to mix the two protocols to that extent. However, the code in both projects are quite similar up to parse_request/parse_handshake is done, and from there one could decide if it is a REST resource or WebSocket-endpoint one communicate with and perform the appropriate action.

**Comment by RobertoMalatesta** [comment]
I agree with Shumen that sometimes (on some configurations) having 2 ports is asking too much.
Is this a planned change?
A plus of having it could be unifying Web and Websocket server into a single project.
Thank you for your time,

R

**Comment by eidheim** [comment]
My only concern is that the implementation will be less clean.

**Comment by RobertoMalatesta** [comment]
I understand your point, it can be more complex as a code but nothing is more complicated than having two projects doing basically the same thing.

**Comment by eidheim** [comment]
You are right that it leads to some extra work having two repositories, but it is two different protocols, which at least traditionally should be running at different ports, and the implementations have slightly different dependencies. But I'll think more on it when the TODO in Simple-WebSocket-Server is resolved.

**Comment by RobertoMalatesta** [comment]
If it helps, civetweb is doing that (got a bug in it btw just now, it seems) and if I remember correctly POCO can switch protocols onto an HTTPServer.

**Comment by moodboom** [comment]
libwebsockets also does http(s) upgrades to ws(s).

**Comment by eidheim** [comment]
As I see it, the problems with combining the two protocols are as follows:
* The libraries have now different dependencies. Boost.context and Boost.coroutine is not needed in Simple-Web-Server, but they are needed in Simple-WebSocket-Server. OpenSSL is also needed for Simple-WebSocket-Server but only for HTTPS in Simple-Web-Server.
* The implementation where the two protocols were combined would be less simple and harder to understand.
* Some HTTP features are not needed in Simple-WebSocket-Server, and one can thus simplify the handling here compared to supporting more HTTP features. This makes Simple-WebSocket-Server a currently bit easier to understand.

**Comment by eidheim** [comment]
It is now possible to upgrade a request from Simple-Web-Server to a Connection in Simple-WebSocket-Server. See https://github.com/eidheim/desktop-stream for an example.
