### ISSUE TITLE
Porting to Android and iOS

### ISSUE THREAD

**Issue by Ninja-007** [eidheim/Simple-Web-Server#130]
Thanks for providing this interesting library. I would like to use it for mobile plateforms.
Before starting I have some questions.

1. Asio comes in two flaviours 1. standalone without boost and second without boost. Is it possible to avoid boost completely? 
2. Are there any REST methods available in the library? 

Regards

**Comment by eidheim** [comment]
1. You can define USE_STANDALONE_ASIO to use the non-boost asio version. The examples will not compile without boost, but you can use the header files. However, there are still some boost dependencies in Client (string_ref and maybe soon shared_mutex), but I'll have a look if there is a way to avoid these if USE_STANDALONE_ASIO is defined.

2. See the examples, you define the REST resources yourself using a method string and a path regex.

**Comment by Ninja-007** [comment]
Thanks you very much for reply. It is encouraging.
Using boost is on mobile platforms is problem while there is no official port and support for it. With C++11 and C++14, many boost things are available. C++14 is officially supported main C++ complieres(e.g. GCC, Clang). 
There are many options on regular platform as compared to mobile platform. It will be great if you create a library(i.e. Client) without boost.

**Comment by eidheim** [comment]
I made the Client independent of boost as well if USE_STANDALONE_ASIO is defined in https://github.com/eidheim/Simple-Web-Server/commit/52ff2787bdea999cbbd74b673c48b35c0f8c4c9a. Note that I have not pushed this to master just yet, some further testing is needed. I'll probably push this commit to master in a few days though.

**Comment by sebt3** [comment]
Well current master can be build and linked without boost, albeit boost headers might be still needed (as I have them on my work environnement)

**Comment by eidheim** [comment]
@sebt3 `boost::string_ref` is used in current master's Client, but this is fixed in the temporary branch async_request.

**Comment by Ninja-007** [comment]
Thanks both you for your replies.

1. Would you mind to enclose all boost headers and special headers in special #ifdef USE_BOOST or #ifndef USE_STANDALONE_ASIO?
2. Does the client have IPv6 support? It is needed for apple store. https://developer.apple.com/support/ipv6/

**Comment by eidheim** [comment]
1. At the moment USE_STANDALONE_ASIO implies no boost, and I think that is ok for now, since the main reason to use other boost headers is that boost.asio uses them. 

2. IPv6 should be supported through asio. We have no IPv4 specific code.

**Comment by Ninja-007** [comment]
Thanks for reply.
1. I hope, when USE_STANDALONE_ASIO is defined, asio does not use any boost headers. Do you have any information on this or should I ask asio developer?
2. Thanks. Do you have any information on this or should I ask asio developer?

**Comment by sebt3** [comment]
@eidheim I know `boost::string_ref` is used in current master, yet that doesn't require to **link** to any boost library ;) all you need is the headers, just like for asio or your library. The issue on mobile is linking not having to take a few header files in your sources :P
@Ninja-007 :
1. Currently you'll need to include boost string_ref header in your projet, but in a few this wont be even needed as eidheim is working on this currently. Setting USE_STANDALONE_ASIO is my current work-case and it works as expected.
2. Never tested IPv6 (just yet) but it should work out of the box by just using an IPv6 address as target address.

**Comment by Ninja-007** [comment]
Thanks @sebt3 
1. I shall wait till complete references to boost removed from master and library becomes totally standalone.
2. It looks like boost asio supports IPv6. I hope, it is present in standalone asio also. http://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/ip__address_v6.html

**Comment by Ninja-007** [comment]
Thanks @sebt3 
2. I checked asio code. It does support IPv6. I shall confirm it later when I submit the app to the apple store.

@eidheim 
I checked the https_examples.cpp and http_examples.cpp. They have HttpClient example at the end of main functions.


I would like to have REST functions like this library(https://github.com/mrtazz/restclient-cpp). Is that OK, if I try to write them and contribute here? Are you ready to accept them? 
restclient-cpp/include/restclient-cpp/connection.h 
restclient-cpp/include/restclient-cpp/restclient.h 

Do you know best way to integrate these functions to your library?

**Comment by eidheim** [comment]
@Ninja-007 I would rather not complicate this library further unless there is a function that is especially needed and is not easy to implement by the library user. I do not see any real value of the api you link to compared to what is offered already by this library, with the possible exception of following redirects.

**Comment by Ninja-007** [comment]
@eidheim 
Thanks for the reply.
I want to write a wrapper(in another file) around this library which will perform 

-   get(const std::string& uri);
-   post(const std::string& uri,  const std::string& data);
-   put(const std::string& uri,   const std::string& data);
-   del(const std::string& uri);
-   head(const std::string& uri);

requests. 

These methods in turn call performCurlRequest(const std::string& uri). I need to find out way to implement it using this library. 
There will not be 1 to 1 implementation. That was the example library. My target is to have REST calls using this library.

**Comment by eidheim** [comment]
@Ninja-007 Sorry, but there are even more HTTP methods, and surely more to come, and what if, for example, someone decides in the future to add content (data) to the get request? Also, what if the `delete` keyword is getting more common than `del` in the future, or the other way around? I would rather just have the general methods we have now, and I might even deprecate the synchronous functions, especially if I would like to wrap the async methods into a JavaScript like Promise library (none exists though yet), and if this becomes the common way to work with asio services in C++. 

However, it is possible to derive the Client<HTTP(S)> classes and implement these methods in your own codebase.

**Comment by Ninja-007** [comment]
I agree with you. My purpose it to make my code available to other people who have similar needs, so that they do not need to write it again. There are many people who are looking for REST library on mobile platforms. But options are few. 
It is your decision about accepting code in the library. I do not and will not agrue about that.

I need to think about implementation of the required methods.

**Comment by Ninja-007** [comment]
I shall close the issue when all boost headers made optional from master code base. I am waiting for that submission. Thanks

**Comment by eidheim** [comment]
Thank you as well. After some extensive testing Today, I might be pushing the above-mentioned commit to master Tomorrow if it still looks good overnight!

**Comment by Ninja-007** [comment]
Is it in master repo?

**Comment by eidheim** [comment]
Yes:)

**Comment by Ninja-007** [comment]
Great, I shall check till next weekend then close the issue.
