### ISSUE TITLE
Client example requests

### ISSUE THREAD

**Issue by Ninja-007** [eidheim/Simple-Web-Server#131]
I have some requests for examples if possible. 
1. Authentication
2. Way to select sync or async 
3. Maximum redirect option and possibilty to disable it
4. Possiblity of aborting request
5. One example with crypto (BTW, does it support LibreSSL? I see some openssl headers in crypto.hpp
.)
6. One simple REST call example. 

Thanks in advance.

**Comment by eidheim** [comment]
1. Authentication is implemented on top of HTTPS, and is not in the scope of this project.
2. See the new examples for async request examples
3. No redirection supported, at the moment you have to implement this on top of this library
4. Set timeouts. Requests are also cancelled when you stop the io_service.
5. The crypto header file is only added for convenience. Asio uses OpenSSL, and that is basically the reason why it is used in the crypto header file.
6. Most important use cases should be shown in the example files I think.

**Comment by eidheim** [comment]
Please have a look at the Response class, the header and content is separated.

**Comment by Ninja-007** [comment]
Thanks,
-Do you have idea on how to download mp3 file(1MB-10MB) from URL? I saw that HTTP has limit on response size. 
-Do you have any plan to implement FTP?

**Comment by Ninja-007** [comment]
This is unmaintained implementation from asio author. He wanted also add couple of feature. This is for reference only.
http://think-async.com/Urdl/doc/html/urdl/planned_features.html

**Comment by eidheim** [comment]
There is a limit on response size? Might be a timeout maybe?

No plans to implement FTP, sorry.
