### ISSUE TITLE
v3.0 - breaking changes

### ISSUE THREAD

**Issue by eidheim** [eidheim/Simple-Web-Server#134]
It is time for a major version bump, and the planned breaking changes are as follows:
* **Critical change**: Current `Server::Request::path` will be split into `path` and `query_string`. This means that for instance `server.resource["^/info$"]["GET"]` will match both `GET /info HTTP/1.1` and `GET /info?a=b HTTP/1.1` requests.  
* ~Callbacks's `std::shared_ptr` parameter types will be changed to ` std::shared_ptr&` in order to avoid unnecessary `std::shared_ptr` copies.~ 
* ~Client and Server public constructors will be replaced with `static ::create` functions that returns `std::shared_ptr`'s. We will take advantage of `std::enable_shared_from_this` to simplify the code in some cases, especially the Client code will be cleaner. Additionally, this will take care that Server and Client objects stay alive until `io_service` tasks using them are finished.~ ~This change depends on if it is possible to use `std::enable_shared_from_this` in both `ServerBase`/`ClientBase` and derived classes.~
* Server::send is moved to Server::Response::send
* Deprecated functions will be removed

Feedback is welcome!

edit: callback's parameters need to be non-const references in order to allow shared_ptr moves. 
edit2: added clang-format file
edit3: .clang-format file has been added to master
edit4: added deprecation warning if query string is present in a resource's regex.
edit5: decided against the deprecation warning if query string is present in a resource's regex to keep the code clean.
edit6: Server::send is moved to Server::Response::send
edit7: Callbacks's `std::shared_ptr` parameter types will stay as is due to no real added value, and a lot of lambda captures would become non-const making it harder for the compiler to optimise.
edit8: the Server and Client constructors will be as before.

**Comment by sebt3** [comment]
Sound all good to me

**Comment by eidheim** [comment]
Update: I removed const from callback's parameters to allow shared_ptr moves.

**Comment by eidheim** [comment]
Update: added clang-format file

**Comment by pboettch** [comment]
Nice choice going to for a clang-format-file. You should mention which version of clang-format you're preferring, as, even with identical `.clang-format`-files, you can get different results.

I, for myself, find it sometimes a bit hard to read the code due to the very, very long lines (even on github you need to scroll horizontally to see them complete). Mostly these long lines come from function or lambda-arguments.  For example:

```C++
///Use this function if you need to recursively send parts of a longer message
void send(const std::shared_ptr<Response> &response, const std::function<void(const error_code&)>& callback=nullptr) const {
  asio::async_write(*response->socket, response->streambuf, [this, response, callback](const error_code& ec, size_t /*bytes_transferred*/) {
    if(callback)
      callback(ec);
  });
}
```
would become

```C++
///Use this function if you need to recursively send parts of a longer message
void send(const std::shared_ptr<Response> &response, 
          const std::function<void(const error_code &)> &callback = nullptr) const {
  asio::async_write(*response->socket,
                    response->streambuf,
                    [this, response, callback](const error_code &ec,
                                               size_t /*bytes_transferred*/) {
                      if (callback)
                        callback(ec);
                    });
}
```
or even
```C++
///Use this function if you need to recursively send parts of a longer message
void send(const std::shared_ptr<Response> &response, 
          const std::function<void(const error_code &)> &callback = nullptr) const {
  asio::async_write(
      *response->socket,
      response->streambuf,
      [this, response, callback](const error_code &ec,
                                 size_t /*bytes_transferred*/) {
        if (callback)
          callback(ec);
      });
}
```
Clang-format handles alignment of arguments (prototypes and calls) very well, but you'd need to break at least one of it manually.

For me this make it easier to read and to understand.

**Comment by eidheim** [comment]
@pboettch Pre C++11 I would agree with you, but now with lambdas and long datatypes it is getting increasingly difficult to read the logic of source code that splits functions into many lines. I think your first example is more readable actually. However, I agree that it is problematic, but the current style is the better of two evils I think.

**Comment by pboettch** [comment]
The first example is a copy-paste from the current http_server.hpp . ;-) - it is the horizontal scrolling which I find the most annoying.

**Comment by eidheim** [comment]
Update: .clang-format file has been added to master

**Comment by eidheim** [comment]
I also just added preference option `source.format_style_on_save_if_style_file_found` for those of us using the [juCi++](https://github.com/cppit/jucipp) IDE.

**Comment by eidheim** [comment]
Update: added deprecation warning if query string is present in a resource's regex after v3.0

**Comment by eidheim** [comment]
Update: decided against the deprecation warning if query string is present in a resource's regex

**Comment by eidheim** [comment]
Update: Server::send will be moved to Server::Response::send

**Comment by eidheim** [comment]
Update: Callbacks's `std::shared_ptr` parameter types will stay as is

**Comment by eidheim** [comment]
Update: the Server and Client constructors will be as before.

**Comment by eidheim** [comment]
Adding a 3.0.0 prerelease now.
