### ISSUE TITLE
CMake cross-platform issues and best practices

### ISSUE THREAD

**Issue by Socapex** [eidheim/Simple-Web-Server#140]
On Windows, there are problems with your build system (-Wextra and such).

For the standard version, the recommended way to set it (cross-platform) is `set(CMAKE_CXX_STANDARD 11)` for example.

For compiler flags, this is a good example :
```
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
	target_compile_options(${PROJECT_NAME} INTERFACE -Wall -Wextra -Wpedantic
		-Werror)

elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
	target_compile_options(${PROJECT_NAME} INTERFACE -Wall -Wextra -Wpedantic
		-Werror)

elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
  # using Intel C++

elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
	target_compile_options(${PROJECT_NAME} INTERFACE /W3)

endif()
```
Good day

**Comment by eidheim** [comment]
`CMAKE_CXX_STANDARD` requires CMake version >= 3.1, and the intel compiler, like clang,  is somewhat compatible with gcc as well (supports `-Wall` and `-Wextra`). I do not use Windows, so I cannot support a Windows only compiler (MSVC), but it is surprising if they do not support the most common gcc warning flags like the rest of the compilers do. If they don't, you cannot expect every project adding these MSVC options, especially when one has no way of testing them. 

I try to keep the CMakeLists.txt as clean and minimalistic as possible, and it serves as an example, easy to read, setup for clang and gcc, in both older and newer systems. I'd like to keep it that way.

**Comment by Socapex** [comment]
Fair enough for the CMAKE_CXX_STANDARD, but I don't believe a little if statement to be very complex. And no, MSVC doesn't support gcc flags :( This was just an example, you can simply check if the compiler is MSVC, and in else add your current flags for the other 3 compilers.

"A very simple, fast, multithreaded, *platform independent* HTTP and HTTPS server"...

I would change the description if you have no desire to support Windows as it is misleading. On the other hand, if you are interested in supporting MSVC but simply can't test, I can send a PR with CMake corrections to support it, but it will contain an if statement! That being said, if you don't support MSVC for other personal reasons, I wont waste my time ;)

Cheers

**Comment by eidheim** [comment]
There has been several merged PR's that added fixes to the source code to make it compile on various MSVC versions. Again, the CMakeLists.txt is just an example, simple and readable, configuration to compile the examples and tests using the most commonly used compilers. Users may not even use CMake, but maybe Meson or Conan instead, or some other build management system, or in your case MSVC with CMake, but I do not have time to support all these various options.

**Comment by Socapex** [comment]
Absolutely, that's why I'm offering help :) I just don't want to spend a ton of time fixing things that wouldn't get accepted for political reasons. Other open-source projects have demonstrated no desire to accept simple fixes for MSVC, because of personal reasons.

Conan is paving the path to extremely simple cross-platform compiling. Having a good cmake file means you could probably easily add SWS to conan-center. I would love that personally, I'm sure it would bring many users. A lot of them Windows devs I would imagine.

**Comment by eidheim** [comment]
I'll consider it again if MSVC gets a `-fno-access-control` equivalent flag. 

One other issue I can think of are potential extra warnings MSVC would give, and I would not be able to test and apply the appropriate flags in the future. 

The main problem I, and probably many other open source developers, have with MSVC and Windows in general, is the extra effort one would have to invest in a Windows only compiler and its exotic OS. Also, the tooling from llvm is getting quite good, cannot clang be used instead of MSVC on Windows? I would think that this would solve quite a few problems, or are there some situations where this is not an option?

**Comment by Socapex** [comment]
My personal tests with clang on windows were marginal at the very best. It is also a huge setup nightmare. C++ with boost is pretty abstracted from the OS btw. The real issue is with C software, not C++.

**Comment by eidheim** [comment]
According to [this](https://www.reddit.com/r/cpp/comments/6mqd2e/why_is_msvc_usually_behind_the_other_compilers_in/dk4ywhm/) it might be worth trying the new clang version 4.0.1.
