### ISSUE TITLE
Inherited friend use

### ISSUE THREAD

**Issue by Socapex** [eidheim/Simple-Web-Server#141]
So I've fixed cmake to build on MSVC (quite simple really, will send PR), which has unearth another problem. I hate to be the bearer of such news :)

At first I thought it was a VS bug, for which I've created a simple test case to demonstrate the issue. I'm beginning to think VS's error is actually correct (who would've thought).

For example : In the test io_test.cpp at line 137, we declare a Connection as such `HttpClient::Connection *connection;`

MSVC will complain Connection is a protected class of ClientBase, which it is. Client is friend of ClientBase (client_http.hpp, line 573), but friend declaration are not inherited ("C++ Standard, section 11.4/8 : Friendship is neither inherited nor transitive.").

I tried compiling my little test case on clang and in fact, it doesn't compile.

```

#include <iostream>

/* Bug? */
template <class T>
struct Base {
protected:
	struct Example {
		int answer = 42;
	};
};

template <class T>
struct Derived : public Base<T> {};

template <>
struct Derived<int> : public Base<int> {
	friend Base<int>;
};

/* Without templates */
struct OtherBase {
protected:
	struct Example {
		int answer = 42;
	};
};

struct OtherDerived : public OtherBase {
	friend OtherBase;
};


int main()
{
	Derived<int>::Example* problem;
	OtherDerived::Example* problem2;

	std::cout << problem->answer << std::endl;
    return 0;
}
```

So I'm curious if I've missed something in Client/ClientBase? My initial assumption was that MSVC is wrong, and if so I'll take it upon myself to contact Microsoft with a bug report and example, but I have only analyzed this issue for a few hours at most.

Good day

**Comment by eidheim** [comment]
Note that `-fno-access-control` is used when compiling the tests. Hopefully MSVC has a similar flag.

**Comment by Socapex** [comment]
Thanks for the info, unfortunately it doesn't. Would you accept something like the following?

ex, io_test.cpp
```
struct WinTest : public HttpClient {
	WinTest(const std::string &server_port_path)
		: HttpClient(server_port_path)
		, connections(HttpClient::connections)
	{}

	using Connection = HttpClient::Connection;
	decltype(HttpClient::connections) connections;// = HttpClient::connections;
};

#ifdef _MSC_VER
using HttpClient = WinTest;
#endif
```

**Comment by eidheim** [comment]
This would be hard for me to maintain, especially when making large changes (like the upcoming v3 release). 

Though, MSVC should really support such an option, since it is essential when writing tests without the tests directing how your API should be. Someone should add an issue request on this to the MSVC team.

**Comment by Socapex** [comment]
I'll take this as a no. Good luck with your project then!
