### ISSUE TITLE
Server seems to work perfectly, but on_error occurs for every request

### ISSUE THREAD

**Issue by connormanning** [eidheim/Simple-Web-Server#146]
I noticed this on my own server application but it occurs for me in the HTTP example as well.  To reproduce, change the `on_error` handler in `http_examples.cpp` to:
```
  server.on_error = [](shared_ptr<HttpServer::Request> /*request*/, const SimpleWeb::error_code & ec) {
    if (ec) std::cout << "Error: " << ec << " " << ec.message() << std::endl;
  };
```

Then run the `http_examples`.

Output will appear like this:
```
$ ./build/http_examples
123
{"firstName": "John","lastName": "Smith","age": 25}
John Smith
Error: system:89 Operation canceled
```

The `Error` log appears after the default `timeout_request` of 5 seconds.  Browsing to http://localhost:8080/info appears to work, but another `Error` line appears 5 seconds every time after that URL is hit.

It appears to me that `asio::async_read_until` at [this line](https://github.com/eidheim/Simple-Web-Server/blob/master/server_http.hpp#L418) never finds the `\r\n\r\n` sequence, and execution proceeds to [this code branch](https://github.com/eidheim/Simple-Web-Server/blob/master/server_http.hpp#L469).  I've tried manually appending `\r\n\r\n` to the content being sent with no change in behavior.

I'm using OS X El Capitan 10.11.6 with Homebrew-installed Boost version 1.64.0_1.  Any insight is appreciated.

**Comment by eidheim** [comment]
At timeout, the async operations are cancelled and on_error is called. One could maybe argue if this is correct behaviour, I decided to pass every error_code to on_error, but you are free to ignore the cancelled error codes in your on_error function.

**Comment by connormanning** [comment]
Thanks for the response.  Can you give a bit of clarification on the `timeout_request` and `timeout_content` configuration items?  If I understand correctly, these represent timeouts for the propagation of the input and output portions of a server request, respectively.

But since the requests always reach the timeout even if the request is very small, it appears that the socket for upload remains open until the `timeout_request` has elapsed, even if the request has been successfully completed.  Does this imply that performance issues are possible when setting these values to zero?  E.g. sockets building up over time?  What will trigger the end of the `asio::async_read_until` in this case?

**Comment by eidheim** [comment]
If the timeouts are not set (zero), the sockets will close when the clients close the sockets. The async_read_until will then run its handler with end of file error code.

**Comment by daniel347x** [comment]
I would suggest putting a note about this in the documentation, for those of us just running the example or a small setup and being confused why the error handler is reached even for successfully handled requests.  This had me confused and thinking I am doing something wrong.  Thanks!

**Comment by eidheim** [comment]
@daniel347x thank you for your suggestion. I added additional comments regarding this in the above commit.
