### ISSUE TITLE
how can I stop processing in simple-web-server side when ajax request abort in frontend 

### ISSUE THREAD

**Issue by xcTorres** [eidheim/Simple-Web-Server#147]

**Comment by eidheim** [comment]
I guess JS's `abort` only stops listening for ajax's request events. If you are doing heavy processing on the server, and would like to stop this processing, you need to implement a way to stop this yourself.

**Comment by xcTorres** [comment]
OK,got it ,thanks. So do you think it is a good way to send a flag to server side and let the server side to terminate the corresponding thread?

**Comment by eidheim** [comment]
This would depend on your application. Closing this issue now since it is related to your application and not the Simple-Web-Server library. Hope you find a good solution though.
