### ISSUE TITLE
http_example, ios::binary

### ISSUE THREAD

**Issue by FlTr** [eidheim/Simple-Web-Server#15]
I think in you're http_example the file should be opened with ios::binary flag. So it is possible to send e.g. images.

**Comment by eidheim** [comment]
You are right, fixed now.

**Comment by eidheim** [comment]
I have been able to send images prior to this, but using the binary flag also takes away for instance all the platform specific stream handling. There might be other issues I do not know about as well that are related to using non-binary input stream.
