### ISSUE TITLE
Limiting size of accepted requests

### ISSUE THREAD

**Issue by sharpie7** [eidheim/Simple-Web-Server#155]
Thanks for writing a very useful tool. It's save me a ton of time on a project I am working on.

One question: is there a configuration to set a maximum size for HTTP requests that the server will attempt to process? For IoT-like REST servers the HTTP requests are normally quite small so we could limit the size accepted. For constrained devices, I am worried that it may be possible for an attacker to force an out-of-memory situation by sending a very large request.

**Comment by eidheim** [comment]
Thank you for reminding me. Right now, the timeouts ensure that the requests cannot be too large, but an idea is to make it possible to set max request size in the config object. I'll have a look in a few days.

**Comment by sharpie7** [comment]
Thanks - for our application a max request size would give me a lot more confidence than just a timeout.

**Comment by sharpie7** [comment]
One additional point: though we are not using the HTTP client currently, we may do in future.

It would also make sense, for the same reasons, to have the option to limit the size of HTTP responses accepted by the client.

**Comment by eidheim** [comment]
A proposed solution can be found in the above commit. Let me know if this looks ok.

**Comment by sharpie7** [comment]
Thanks - the principle looks good, and I think this is a valuable enhancement.

One question: what does "Exceeding this limit will result in a message_size error code" exactly mean? An error code from where, to where?

**Comment by eidheim** [comment]
The server will use the on_error callback with the message_size error code set, and the client will either throw or use a callback with the message_size error depending on if one use sync or async request calls. 

There are some issues with the above commit that I'll fix however. It will change slightly.

**Comment by eidheim** [comment]
The issues should be fixed in https://github.com/eidheim/Simple-Web-Server/commit/2d2b73d6a11cdfc2f10dde3900850163fed75d7e.

**Comment by sharpie7** [comment]
Thanks agin - this is a useful step forward. 

For my application I think a different error handling would be more appropriate. I see a message that is too big for my application, but doesn't crash the server, as a 'soft' error that would likely get a 4XX response. In the error call-back I don't have the context to send a 4XX response so I guess this is not possible.

Could there be the option to pass the data that was accepted to the normal call-back, perhaps with a flag to indicate that additional data was ignored?

**Comment by eidheim** [comment]
Thank you for the feedback. After some thought, I think the solution is for the server to automatically respond with a 413 error and close the connection. From https://tools.ietf.org/html/rfc2616#section-10.4.14:
"The server is refusing to process a request because the request
   entity is larger than the server is willing or able to process. The
   server MAY close the connection to prevent the client from continuing
   the request."

`on_error` will still be called, but the resource callback will not be called. What do you think about this solution?

**Comment by sharpie7** [comment]
Yes, for requests that sounds like a good solution to me which is in-line
with the RFC.

What about the size of responses? I guess in that case we can just call
on_error as there is no communication back to the source.

Regards

Iain

**Comment by eidheim** [comment]
I added 413 responses and did a rebase. The changes can be seen in the above commit. Further feedback is welcome!

My initial thought is that it should be up to the library user to limit their response if needed.

**Comment by eidheim** [comment]
I added a slightly different condition check when `async_read_until` is used.

**Comment by Shashirathod7** [comment]
Thank you for the response.

Would be glad to know more about the project


Rgds
Sashidhar Rathod

**Comment by sharpie7** [comment]
@eidheim Thanks for the fixes. I see you have addressed request size for the server and response size for the client which is what I think is needed.

I agree that for the server it is up to the library user to limit the size of the response it requests.

At the moment this looks good to me, but I will test on my application in the next few days (time permitting).

**Comment by eidheim** [comment]
@sharpie7 Thank you again for looking into this. I'll wait with pushing these changes to master until I hear how your tests go.

**Comment by sharpie7** [comment]
Just hit one problem when compiling with server_http.hpp - you seem to be missing a "#include <mutex>" needed to defined std::unique_lock() . Not sure how you didn't pick that up in your tests - may be just appears because I am using ASIO standalone rather than Boost.

**Comment by sharpie7** [comment]
With the `#include` fixed the changes to server_http.hpp work great in my application thanks. I haven't tested the other classes as I am currently not using them, but I will be looking at bringing in the client and https over the next 1-2 months. I suggest you fix the `#include` and merge with master.

The changes did make me think of one other point, but as it is a bit off-topic I will create a new issue.

Thanks again. Helps me a lot.

**Comment by sharpie7** [comment]
BTW, for those interested the project using the server is now available here:
http://os-iot.org/

Current version in master branch doesn't have the size limited implemented, but I do have a sub branch with the size limit implemented.

**Comment by eidheim** [comment]
@sharpie7 Thank you again. I added the missing include, strange that the tests worked without it since I do run the tests with standalone asio as well, but it might be that a newer asio header includes this. 

I'll have a second look at the changes and push to master if all looks well.
