### ISSUE TITLE
Crashing unexpected

### ISSUE THREAD

**Issue by FlTr** [eidheim/Simple-Web-Server#16]
Environment:
- Win7
- boost 1.59
- VS 2015 community

Both, the http_example and my application, which implements more or less similiar the default_resource example are crashing unexpected when a request appears.

Most times VS sais there was a exception in 'ucrtbase.dll' / 'ucrtbased.dll'. Sometimes it points towards the first statement in default_resource lambda to be executed next.

Commenting those lines, solves the problem somehow:

```
if(length>buffer_size) {
    vector<char> buffer(buffer_size);
    size_t read_length;
    while((read_length=ifs.read(&buffer[0], buffer_size).gcount())>0) {
        response.stream.write(&buffer[0], read_length);
        response << HttpServer::flush;
    }
}
```
I will test you're new commit in the evening.

**Comment by eidheim** [comment]
Yeah, I think the latest commits have solved this.

**Comment by FlTr** [comment]
Tested it. First no difference, but now i got it.

It is the "more or less similiar". The problem was my interpretation of your example and the decision pro std::array and contra std::vector. 128KB stack memory allocation seems to be the problem. With std::vector or dynamically allocated std::array it works.

Thanks for great lib and support.
