### ISSUE TITLE
it can support gzip or deflate compress?

### ISSUE THREAD

**Issue by fawdlstty** [eidheim/Simple-Web-Server#164]
hello engineers,
i think the tools needs the compress functions, can it support this?

**Comment by eidheim** [comment]
At least for HTTP/1.1 one would implement compression on top of this library using for instance zlib. For more information look here: https://en.wikipedia.org/wiki/HTTP_compression. 

One option could be to add wrapper functions for some zlib encryption algorithms in a compression header (like `crypto.hpp`) to make it easier for users to add compression support using Simple-Web-Server. If someone has experience with zlib, feel free to create a PR on this.

**Comment by fawdlstty** [comment]
i have a question that the server_http response,such as:
`m_server.resource ["^/test.cfm$"]["GET"] = [] (std::shared_ptr<HttpServer::Response> response, std::shared_ptr<HttpServer::Request> request) {
    // in this function, request.remote_endpoint_address and request.remote_endpoint_port are always null
}`
 How should I fix it?

**Comment by eidheim** [comment]
This is actually a bug, thank you for reporting it. The address and port are read before async_accept. I’ll fix it Tomorrow.

**Comment by eidheim** [comment]
@fawdlstty The issue you mentioned should be fixed now. See the above commit.

**Comment by fawdlstty** [comment]
thanks. 说英文真累我还是说中文好了。我觉得这项目挺厉害的，几个文件就能实现这么强大的功能，但我觉得这项目的架构可以再优化一下。最近fork了这个项目，等有时间也来改一改

**Comment by vitor-alves** [comment]
Thanks for fixing remote_endpoint_address
I have faced this problem a few moments ago

**Comment by eidheim** [comment]
Regarding compression/decompression, Boost::Iostreams seems to support bzip2, gzip, and zlib that already works on streams (http://www.boost.org/doc/libs/1_65_1/libs/iostreams/doc/index.html).
