### ISSUE TITLE
Hooks for timing?

### ISSUE THREAD

**Issue by RobertHenry6bev** [eidheim/Simple-Web-Server#169]
Are there any mechanisms for collecting the time in the server spent on a request/response?

**Comment by eidheim** [comment]
An interesting idea, and I'll give it some thought, but this is not something that has been implemented yet.

**Comment by SethHamilton** [comment]
I would like something similar, at least the time of the accept. I could calculate the rest as difference from that time.

**Comment by eidheim** [comment]
Good point @SethHamilton I'm thinking one could store the time a request is read (before its content is read) in a variable in `Server::Request`, and from there one could look at differences from this time. One can also time respond sends oneself using `Server::Respond::send()`.
