### ISSUE TITLE
Users of Simple Web Server

### ISSUE THREAD

**Issue by ya1gaurav** [eidheim/Simple-Web-Server#17]
Are there known users of Simple web server?
Who are its competitors ? lighttpd ?

**Comment by eidheim** [comment]
I do not know of any other small library like this that makes it simple to implement REST resources in modern C++ applications. Keep in mind that this is a HTTP(S) library, and not a web server software (like lighttpd). For instance, one never needs to create a new process in this library to respond to a HTTP request. 

When it comes to users, I only know about those that have written issues on this Github repository.
