### ISSUE TITLE
Redirecting HTTP to HTTPS

### ISSUE THREAD

**Issue by alandefreitas** [eidheim/Simple-Web-Server#171]
I'm sorry if that's a stupid question but... when I run a Server<SimpleWeb::HTTPS>, can I redirect a request from http://localhost:8080/ to https://localhost:8080/ without creating two servers?

**Comment by eidheim** [comment]
Not a stupid question at all, but currently one would need one server for each port you wish to accept connections on. That is, in your case you would need two servers.

**Comment by eidheim** [comment]
But both servers can of course share the same `asio::io_service` if that is favourable.

**Comment by eidheim** [comment]
Oh, you need to different ports for HTTP and HTTPS. Defaults are 80 for HTTP, and 443 for HTTPS.
