### ISSUE TITLE
How Can I use http server with thread pool.

### ISSUE THREAD

**Issue by hedemonde** [eidheim/Simple-Web-Server#179]
in example a server thread like this :
    thread server_thread([&server]() {
    // Start server
    server.start();
  });

I want use it in a thread pool
 I make a simple test like this : 
   thread server_thread1([&server]() {
    // Start server
    server.start();
  });

  
  thread server_thread2([&server]() {
    // Start server
    server.start();
  });

it could not work 
What should I do?

**Comment by eidheim** [comment]
Please use `server.config.thread_pool_size = 3` for instance.
