### ISSUE TITLE
Client doesn't close connection properly

### ISSUE THREAD

**Issue by Pit-m** [eidheim/Simple-Web-Server#180]
Hi,
I'm trying to exchange data between one server and one client. At the first connection, it works well but after few seconds (around 5s, could it be the server time out?), the connection is closed and the client only return error (pipe broken). 
Using wireshark, I can see this communication : server  => FIN + ACK, client => ACK, server => RST. Is it normal that the client doesn't send FIN message? Is this why I get this error after?

**Comment by eidheim** [comment]
The client keeps the connection open in case you will do another request. This is for optimisation purposes, since opening another socket for a second request is more expensive than doing another request on the same socket. On the other hand, if you would like to close the connection, you should use the `Connection: close` header field when performing a request.

**Comment by Pit-m** [comment]
In client_http.hpp, I don't see any `Connection: close`, may it be `ClientBase::stop` ?
Is there an option on `Server` to don't let it close the connection?

**Comment by eidheim** [comment]
To close a connection after a request, you can either do:
```c++
HttpClient client("localhost:8080");
auto r = client.request("GET", "/match/123", "", {{"Connection", "close"}}); // Server will close the connection
cout << r->content.string() << endl;
```
or:
```c++
HttpClient client("localhost:8080");
auto r = client.request("GET", "/match/123");
cout << r->content.string() << endl;
client.stop(); // Client closes the connection
```
or combining them might be the most clean approach:
```c++
HttpClient client("localhost:8080");
auto r = client.request("GET", "/match/123", "", {{"Connection", "close"}});
cout << r->content.string() << endl;
client.stop();
```

**Comment by Pit-m** [comment]
Ok. I used the second option. I think this issue can be closed. Thank you.
