### ISSUE TITLE
Do We have a method like urlencode?

### ISSUE THREAD

**Issue by hedemonde** [eidheim/Simple-Web-Server#183]
hi:
   I want to transform something like this:
   "ImgUrl": another url
  but android client failed to decode the response.
  so I need encode the imgurl before it sended.
  I try to find an encode method, but i can't. 
   Is here has some method to do this thing?
thank you !

**Comment by eidheim** [comment]
I think you are looking for this: https://github.com/eidheim/Simple-Web-Server/blob/master/utility.hpp#L87 or https://github.com/eidheim/Simple-Web-Server/blob/master/utility.hpp#L42. You can also encode/decode using Base64: https://github.com/eidheim/Simple-Web-Server/blob/master/crypto.hpp#L30

**Comment by hedemonde** [comment]
thank you!
