### ISSUE TITLE
Turning numbers into %xx

### ISSUE THREAD

**Issue by SethHamilton** [eidheim/Simple-Web-Server#184]
https://github.com/eidheim/Simple-Web-Server/blob/1552cdc11acf0baedceb1e146824411506fc12d7/utility.hpp#L51

I think line could be:
```
else if (!((chr >= '0' && chr <= '9') || (chr >= 'A' && chr <= 'Z') || (chr >= 'a' && chr <= 'z') || chr == '-' || chr == '_'))
```
Basically `0-9`, `a-z`, `A-Z` and `-` and `_` are all good to go.

**Comment by eidheim** [comment]
UTF-8 characters of 2 or more bytes should not be percent encoded I think, but they would be included in your expression if I'm not mistaken.

**Comment by SethHamilton** [comment]
Sorry for the late response. I'm not certain UTF-8 must be encoded, but both your current code and my example don't take this into account. the issue I have with the current code is this that parameters that are simply numeric (and valid) like `someparam=123` are being encoded, and that isn't great (reduced readability and overhead).

**Comment by eidheim** [comment]
Thank you, after some additional reading I modified your expression by adding a couple more characters (according to http://www.ietf.org/rfc/rfc3986.txt), and added more tests. Your issue should now be fixed.

**Comment by SethHamilton** [comment]
@eidheim thank you kindly.
