### ISSUE TITLE
When set thread pool size to >1, but CPU usage only 25

### ISSUE THREAD

**Issue by chenzx** [eidheim/Simple-Web-Server#201]
When set thread pool size to >1, but CPU usage only 25, means these threads are all running on a single hard cpu core?

'''
  HttpServer server;
  server.config.port = 9999;
  server.config.reuse_address = true;
  server.config.thread_pool_size = 5;
  server.config.timeout_request = 300;
  server.config.timeout_content = 600;
'''

**Comment by chenzx** [comment]
I see it in Window's process manager,

In Performance > CPU Usage, all 4 cpu cores seem active,

But in Process > "CPU" column, the value is at most 25.

**Comment by eidheim** [comment]
Multiple threads can run on one core, but if two threads is executing tasks simultaneously, they would need 2 cores. 

Your CPU usage would depend on Asio internals and the load of the server. Other than that you are on your own here, at least I am of no more help I think, especially on Windows.

**Comment by chenzx** [comment]
Thanks for rely.
After i use python scripts to do concurrent requests, the CPU usage now
goes to >25.
So it's due to previous sequential requests.

2018-01-17 19:30 GMT+08:00 Ole Christian Eidheim <notifications@github.com>:
