### ISSUE TITLE
Fully loads one kernel

### ISSUE THREAD

**Issue by FarafontovDmitriy** [eidheim/Simple-Web-Server#205]
I use asio standalone. The following code fully loads one kernel my CPU. This happens after the GET request comes.
`HttpServer server;

	server.config.port = 80;

	server.default_resource["GET"] = [hModule](shared_ptr<HttpServer::Response> response, shared_ptr<HttpServer::Request> request) {
		string strRequest = request->content.string();
		p7Trace->P7_INFO(hModule, TM("%ls"), W_C_STR(strRequest));
		*response << *driversManager.GetResponse(strRequest).get();
	};
	
	server.start();`
This only happens when using the latest version asio (from https://github.com/chriskohlhoff/asio).

**Comment by FarafontovDmitriy** [comment]
Issue can be closed. The problem was created by the P7 logging library

**Comment by eidheim** [comment]
Glad you figured it out
