### ISSUE TITLE
Http client with partial results

### ISSUE THREAD

**Issue by Type1J** [eidheim/Simple-Web-Server#227]
I have a large dynamically generated file that I want to parse as it's being downloaded. I have a parser hooked to a downloader that I wrote directly in asio, but since it's an http request, I'd like to rewrite it to be more maintainable. However, I'm not sure how to get the SimpleWeb::Client to yield partial results. I'd like an example, but I'd be happy with a comment here describing what to do. Thanks!

**Comment by eidheim** [comment]
Since the client waits for the entire request/response to finish before you can process the response, you have to make your own modifications this this library for this particular use case.

**Comment by Type1J** [comment]
Ok
