### ISSUE TITLE
Please make context, coroutine an optional dependency

### ISSUE THREAD

**Issue by jwaterloo** [eidheim/Simple-Web-Server#24]
boost context and by extension coroutine on MSVC requires MASM to build. MASM only comes with Visual Studio 2005 which is far behind 2014 and difficult to obtain. If possible please detect context and coroutine, other wise fall back on just threads. If that is not possible a CMAKE option would be an acceptable alternative.

**Comment by eidheim** [comment]
Coroutine is needed to send several responses to the client in one request using Response::flush. Without coroutine, this operation would be very difficult to perform correctly. Combined with the boost asio thread pool, I can't at the moment see how it can be done without coroutine actually. 

But boost is widely used, and it seems strange that newer versions of Visual Studio are not supported. If MSYS2, however, is an option for you on Windows, I would use that instead, as it contains precompiled library packages for the most commonly used libraries, including boost. Although, do not expect Linux-like stability and speed from MSYS2. 

If MSVC is still needed, it might help posting an issue at Boost about the boost coroutine build problems on newer MSVC versions. I am not sure how widely used Boost.Coroutine is, so there might not be an already reported issue on this.

**Comment by hansenms** [comment]
First thanks for making this project, I learned a lot from reading the code.

I have a related problem with coroutine. I was trying to take your webserver and put in in a shared library to be part of a larger project (https://github.com/gadgetron/gadgetron). It works fine on my mac but on Ubuntu 14.04 (one of our reference platforms), I get the following error:

    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_coroutine.a(standard_stack_allocator_posix.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC

The problem seems to be that libboost_coroutine is only a static library on Ubuntu 14.04 (there is no *.so version) and hence the error. While this is not a problem with your project as such, it makes it harder to use on Ubuntu 14.04 because one would have to tinker with Boost in order to include it in a shared library. 

I was wondering if you had tried this and have any thoughts on the best strategy?

**Comment by eidheim** [comment]
Just tried to reproduce this problem on Ubuntu 14, but the source links without the problem you are experiencing. I have, however, done `sudo add-apt-repository ppa:ubuntu-toolchain-r/test` previously, but downgraded my boost and g++ to libboost-1.54 and g++-4.8. CMake should take care of the library linking. Do you get any error messages when running `cmake .`?

**Comment by eidheim** [comment]
You could try to add the libboost_coroutine.a (the whole path) to with target_link_libraries after doing add_library if you use cmake to create the shared library. Think I had a similar issue when creating a shared library some months back.

**Comment by eidheim** [comment]
Debian testing also only contains the libboost_coroutine.a file, that is no .so file, so the problem might not be related to this I think?

**Comment by hansenms** [comment]
I have forked your repo and added a small example that demonstrates the problem:

https://github.com/hansenms/Simple-Web-Server/tree/link_problem

When try to build that I get:

```
cmake ../
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   regex
--   system
--   thread
--   coroutine
--   context
--   filesystem
--   date_time
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hansenms/temp/Simple-Web-Server/build
hansenms@grenada:~/temp/Simple-Web-Server/build$ make
Scanning dependencies of target http_examples
[ 25%] Building CXX object CMakeFiles/http_examples.dir/http_examples.cpp.o
Linking CXX executable http_examples
[ 25%] Built target http_examples
Scanning dependencies of target test_library
[ 50%] Building CXX object CMakeFiles/test_library.dir/test_library.cpp.o
Linking CXX shared library libtest_library.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_coroutine.a(standard_stack_allocator_posix.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_coroutine.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libtest_library.so] Error 1
make[1]: *** [CMakeFiles/test_library.dir/all] Error 2
make: *** [all] Error 2
```

When you created a library was it a shared library or a static one? Not quite sure what is going on here, just thinking out loud. Any hints would be appreciated.

**Comment by hansenms** [comment]
Check also this:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802509

**Comment by eidheim** [comment]
Thank you for the test case and the debian bugreport, it made things abit easier. I need to learn more about static and shared linking it seems. 

The library I created some months back was shared, but I had access to all the needed shared libraries, so it worked without this problem. 

However, I also found this: https://web.archive.org/web/20150319085301/http://www.gentoo.org/proj/en/base/amd64/howtos/index.xml?part=1&chap=3
And it says: "Sometimes it is also the case that a library isn't intended to be a shared library at all, e.g. because it makes heavy usage of global variables. In this case the solution is to turn the to-be-built shared library into a static one.". I tried your fork, and changed line 46 of CMakeLists.txt into: `add_library(test_library STATIC test_library.cpp)`. Is this an acceptable solution in your case?

**Comment by hansenms** [comment]
Unfortunately this library has to be shared. I have tried to create a singleton for the whole application and it is used by the main executable and multiple plugins that are linked at runtime (plugins). On Windows, this is a hassle because of the way heaps are organized, so I have to have this shared library with a single instance variable for the singleton. It must be a shared library.

It is a shame because the coroutine thing is really a Debian bug but at this stage, it would be a lot to ask of our users to recompile Boost themselves. So I can't really see a good way through this. 

I'll keep an eye on it for the future though.

**Comment by jinchaoh** [comment]
First thanks for creating this project, and I am from China .
Could you help me to fix my trouble , may be it was cause by my boost lib.

 When try to build that I get as following:

make all
[ 33%] Building CXX object CMakeFiles/http_examples.dir/http_examples.cpp.o
Linking CXX executable http_examples
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)’中：
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockEb[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockEb]+0x2c)：对‘boost::re_detail_106000::put_mem_block(void*)’未定义的引用
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘void boost::re_detail_106000::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type)’中：
http_examples.cpp:(.text._ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE[_ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE]+0x8d)：对‘boost::re_detail_106000::get_default_error_string(boost::regex_constants::error_type)’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE[_ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE]+0xc1)：对‘boost::re_detail_106000::raise_runtime_error(std::runtime_error const&)’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE[_ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE]+0xdb)：对‘boost::re_detail_106000::get_default_error_string(boost::regex_constants::error_type)’未定义的引用
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()’中：
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv]+0x18)：对‘boost::re_detail_106000::get_mem_block()’未定义的引用
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_imp()’中：
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0xc)：对‘boost::re_detail_106000::get_mem_block()’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x1ae)：对‘boost::re_detail_106000::verify_options(unsigned int, boost::regex_constants::_match_flags)’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x274)：对‘boost::re_detail_106000::put_mem_block(void*)’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x458)：对‘boost::re_detail_106000::put_mem_block(void*)’未定义的引用
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘__gnu_cxx::__normal_iterator<char const*, std::string> boost::re_detail_106000::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::string>, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::re_detail_106000::re_set_long<unsigned int> const*, boost::re_detail_106000::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)’中：
http_examples.cpp:(.text._ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x182)：对‘boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const’未定义的引用
http_examples.cpp:(.text._ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcSsEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SB_SB_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x4af)：对‘boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const’未定义的引用
CMakeFiles/http_examples.dir/http_examples.cpp.o：在函数‘SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::find_resource(std::shared_ptr<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::Request>)’中：
http_examples.cpp:(.text._ZN9SimpleWeb10ServerBaseIN5boost4asio19basic_stream_socketINS2_2ip3tcpENS2_21stream_socket_serviceIS5_EEEEE13find_resourceESt10shared_ptrIS8_ESA_INS9_7RequestEE[_ZN9SimpleWeb10ServerBaseIN5boost4asio19basic_stream_socketINS2_2ip3tcpENS2_21stream_socket_serviceIS5_EEEEE13find_resourceESt10shared_ptrIS8_ESA_INS9_7RequestEE]+0x31c)：对‘boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)’未定义的引用
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libboost_coroutine.a(stack_traits.o)：在函数‘void boost::call_once<void (*)(unsigned long*), unsigned long*>(boost::once_flag&, void (*)(unsigned long*), unsigned long*)’中：
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:164：对‘boost::thread_detail::enter_once_region(boost::once_flag&)’未定义的引用
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:176：对‘boost::thread_detail::commit_once_region(boost::once_flag&)’未定义的引用
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:172：对‘boost::thread_detail::rollback_once_region(boost::once_flag&)’未定义的引用
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libboost_coroutine.a(stack_traits.o)：在函数‘void boost::call_once<void (*)(rlimit*), rlimit*>(boost::once_flag&, void (*)(rlimit*), rlimit*)’中：
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:164：对‘boost::thread_detail::enter_once_region(boost::once_flag&)’未定义的引用
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:176：对‘boost::thread_detail::commit_once_region(boost::once_flag&)’未定义的引用
/home/hankin/Downloads/boost_1_60_0/./boost/thread/pthread/once_atomic.hpp:172：对‘boost::thread_detail::rollback_once_region(boost::once_flag&)’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [http_examples] 错误 1
make[1]: *** [CMakeFiles/http_examples.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by eidheim** [comment]
Seems like the boost libraries are not correctly linked. Could you add `message("Boost libraries: ${Boost_LIBRARIES}")` at the end of CMakeLists.txt, and post here the output of running `cmake .` again.

**Comment by eidheim** [comment]
context and coroutine are no longer dependencies
