### ISSUE TITLE
How to set the timeout value for the client request ?

### ISSUE THREAD

**Issue by pengweichu** [eidheim/Simple-Web-Server#31]
Hello, I have two questions need help:
1. When I use HttpClient to POST/GET to server, how to set the timeout if the server doesn't respond in a given time  then the HttpClient will returned once the request is timeout ?
2. It's possible to make the HttpClient works as asynchronous mode ?

Thanks & regards,

**Comment by eidheim** [comment]
1. The client was implemented as simple as possible, and have to change it abit to support timeouts. Found this blog post on how to do it: http://bicosyes.com/2009/12/boostasio-synchronous-read-with-timeout/. I'll try to find time for it in a week or two, unless someone beats me to it with a pull request. 

2. In order to make the HttpClient work asynchronously, you can start it in a thread, pass a callback to the thread, and run this callback when the client finishes with appropriate parameters. This is the typical way to make a synchronous function asynchronous. Use std::shared_ptr to keep track of your resources (as you do not know when they run out of scope). Do some googling on the subjects if you are unsure. It is well worth knowing:)

**Comment by pengweichu** [comment]
I have been make a patch to set the timeout for send and recv, but don't know how to send the PR, below is my code:

	class timeout_op
	{
	public:
		timeout_op(unsigned int timeout, int _name)
			:timeout_value(timeout),
			op_name(_name) 
		{
	
		};

		template<class Protocol>
		int level(const Protocol& p) const { return SOL_SOCKET; }

		template<class Protocol>
		int name(const Protocol& p) const { return op_name; }

		template<class Protocol>
		const void* data(const Protocol& p) const { return &timeout_value; }

		template<class Protocol>
		size_t size(const Protocol& p) const { return sizeof(timeout_value); }

	private:
		unsigned int timeout_value;
		int op_name; // SO_SNDTIMEO or SO_RCVTIMEO
	};


    typedef boost::asio::ip::tcp::socket HTTP;
    
    template<>
    class Client<HTTP> : public ClientBase<HTTP> {
    public:
        Client(const std::string& server_port_path, unsigned int s_timeout = 0, unsigned int r_timeout = 0) 
			: ClientBase<HTTP>::ClientBase(server_port_path, 80),
			send_timeout(s_timeout),
			recv_timeout(r_timeout)
			{
            socket=std::make_shared<HTTP>(asio_io_service);
        }
        
    private:
        void connect() {
            if(socket_error || !socket->is_open()) {
                boost::asio::ip::tcp::resolver::query query(host, std::to_string(port));
                boost::asio::connect(*socket, asio_resolver.resolve(query));
                
                boost::asio::ip::tcp::no_delay option(true);
                socket->set_option(option);

				// For Linux  does the time_out need to be /1000 ?
				if (send_timeout > 0)
				{
					timeout_op send_op(send_timeout, SO_SNDTIMEO);
					socket->set_option(send_op);
				}

				if (recv_timeout > 0)
				{
					timeout_op recv_op(recv_timeout, SO_RCVTIMEO);
					socket->set_option(recv_op);
				}
                
                socket_error=false;
            }
        }

		unsigned int send_timeout;
		unsigned int recv_timeout;
    };

**Comment by eidheim** [comment]
This looks like a good solution, do you know if it is platform independent? Strange that this way is not shown in the Boost.Asio examples, at least not to my knowledge. What platform are you on?

**Comment by pengweichu** [comment]
I'm using the Windows, it's Windows 10 + VS2013.

Please see this docmentation: 
http://think-async.com/Asio/boost_asio_1_3_0/doc/html/boost_asio/reference/SettableSocketOption.html

**Comment by eidheim** [comment]
Fixed in https://github.com/eidheim/Simple-Web-Server/commit/8a73cb381a79d21290522ce0cbf9be3dff78bd48
