### ISSUE TITLE
Can't access the same resource in concurrent way

### ISSUE THREAD

**Issue by pengweichu** [eidheim/Simple-Web-Server#32]
Hello, it's seems the server doesn't support the client access the same resource in concurrent before the previous operation is not returned ?

For example here has the resource: http://192.168.0.28/match/123, I use the Chrome to access it, the server takes a few seconds say 10 seconds to find the process this request likes query database. During that if I use firefox to access http://192.168.0.28/match/123, seems the resource handle function didn't called until the first operation returned.

**Comment by eidheim** [comment]
This is typical when the thread pool gets busy, however, you can use Response::flush to temporarily release the resource from the thread pool so that other threads can perform their tasks.

**Comment by pengweichu** [comment]
It's not help to me, the second request doesn't goes to here before the sleep end.

	server.resource["^/match/([0-9]+)$"]["GET"] = [](SimpleWeb::Server<socket_type>::Response& response, shared_ptr<SimpleWeb::Server<socket_type>::Request> request) {
		string number = request->path_match[1];

		response.flush();
		Sleep(1000 * 20);

	response << "HTTP/1.1 200 OK\r\nContent-Length: " << number.length() << "\r\n\r\n" << number;
	};

**Comment by eidheim** [comment]
The only way to work around this, that is having one thread per resource request, is to increase the thread pool size (see the Server-constructor).

**Comment by eidheim** [comment]
See the heavy work example
