### ISSUE TITLE
Can't use an output-only stream as request content

### ISSUE THREAD

**Issue by wdx04** [eidheim/Simple-Web-Server#33]
Hi eidheim,

In client_http.h, ClientBase::request function is declared as:
```C++
std::shared_ptr<Response> request(const std::string& request_type, const std::string& path, std::ostream& content, 
const std::map<std::string, std::string>& header=std::map<std::string, std::string>())
```
But if we actually use an output-only stream like std::ostringstream for content, the request would fail because content.rdbuf() would return an empty buffer. 
You can examine the behavior by changing the following line in http_examples.cpp:
```C++
stringstream ss(json);
```
to
```C++
ostringstream ss(json);
```
Running the modified program will make the main thread hang at the subsequent client request call.
My solution: change content's declared type to std::iostream&, enforcing it to be a input-output stream.
Also, please consider adding some overloads of the request function to support other content types, such as boost::string_ref.

Thanks.

**Comment by eidheim** [comment]
Splendid, I'll fix this Tomorrow hopefully. 

Have never actually used boost::string_ref, but I'll have a look at it (trying as far as possible to stick to std::). When you say overloads to the request function, you mean add string type template for the first two parameters? Or add one declaration specifically for boost::string_ref? Not sure one would notice the optimisation from using boost::string_ref instead of const std::string& here though.

**Comment by eidheim** [comment]
Or can just as well template the first two arguments, as backward compability will be kept if I am not mistaken.

**Comment by wdx04** [comment]
I mean we can use boost::string_ref for the third argument, to avoid unnecessary copying of the post content in some situations, it may provide some performance benefits when the size of content is large.
For example, I want to post some Json data generated from Qt's QJsonDocument, now I have to write:
```C++
QByteArray req_content = myJsonDocument.toJson();
std::stringstream req_body_stream;
req_body_stream.write(req_content.constData(), req_content.length()); // copying content
auto response = client.request("POST", req_path, req_body_stream, headers);
```
If we have an overload of boost::string_ref conent, above code can be changed into
```C++
QByteArray req_content = myJsonDocument.toJson();
boost::string_ref req_content_ref(req_content.constData(), req_content.length()); // no copying
auto response = client.request("POST", req_path, req_content_ref, headers);
```
boost::string_ref have a similar interface to std::string, internally it has only 2 data members: a const char * buffer pointer and a length, so it can be constructed and copied efficiently.

**Comment by eidheim** [comment]
The first issue is fixed: content parameter in Client::request is now of type std::iostream (https://github.com/eidheim/Simple-Web-Server/commit/99204ec73dd59d310f55e0c38e5e898479455fa8)
