### ISSUE TITLE
Request to simplify the resource definition

### ISSUE THREAD

**Issue by SumolX** [eidheim/Simple-Web-Server#34]
I'm finding it very wordy and tedious to keep typing the resource signature for all my callback handlers.  With my copy of your library I've replaced the following lines and I'm hoping this could be pushed into your tree in one form or another.

```
    typedef std::function<void(typename ServerBase<socket_type>::Response&, std::shared_ptr<typename ServerBase<socket_type>::Request>)> Resource;

    std::unordered_map<std::string, std::unordered_map<std::string, Resource>>  resource;
    std::unordered_map<std::string, Resource> default_resource;

private:
    std::vector<std::pair<std::string, std::vector<std::pair<boost::regex, Resource>>>> opt_resource;
```

**Comment by eidheim** [comment]
Sorry for the really late reply! Have looked at this several times and I can't decide. However, I guess you could just as well add this typedef on top of your cpp file using Simple-Web-Server (for instance http_examples.cpp).
