### ISSUE TITLE
Http server is case-sensitive when reading Content-Length

### ISSUE THREAD

**Issue by simonnilsson** [eidheim/Simple-Web-Server#35]
If a request is made using "content-length" header name in lower case the server does not recognize it.

HTTP header names are case-insensitive, according to [RFC2616](http://www.ietf.org/rfc/rfc2616.txt) 

Using find_if with a case-insensitive comparison could be used to solve this.

**Comment by eidheim** [comment]
You are right. I'll have a look at it when I got time, but feel free to make a pull request for this.
