### ISSUE TITLE
terminate of 'std::invalid_argument', what():  read: End of file

### ISSUE THREAD

**Issue by psy2013GitHub** [eidheim/Simple-Web-Server#38]
hi, 
     as in the title, i came across a error in:
     json_string =  "{\"task_name\": \"ngram\", \"params\": [\"%E8%80%81%E5%90%8C%E5%AD%A6\", \"2\"]}"
     response << "HTTP/1.1 200 OK\r\nContent-Length: " << line.length() << "\r\n\r\n" << json_string;

    can you help me ;), thank you very mych.

**Comment by eidheim** [comment]
replace line.length with json_string.length if I am not mistaken?

**Comment by psy2013GitHub** [comment]
sorry for my careless, line is another string which did not bother much, i guess the problem lines in json_string. can you try it ;)

**Comment by psy2013GitHub** [comment]
also, i try to modify response in **server.resource["^/json$"]["POST"]** of **http_examples.hpp** as follows:
       response << "HTTP/1.1 200 OK\r\nContent-Length: " << name.length() << "\r\n\r\n" **<< "{\"task_name\": \"ngram\", \"params\": [\"%E8%80%81%E5%90%8C%E5%AD%A6\", \"2\"]}";**

same **end of file** error still exists.

 hope you can help me.

**Comment by psy2013GitHub** [comment]
the problem lies in request_read method of class BaseClient of client_http.hpp, the code block is:
if(response->header.count("Content-Length")>0) {
                    boost::asio::read(*socket, response->content_buffer,
                            boost::asio::transfer_exactly(stoull(response->header["Content-Length"])-num_additional_bytes));
                }
the problem seems lies in boost:asio::read, can you fix it, thanks

**Comment by eidheim** [comment]
Seems like you are using an old version. Please get the new one: git clone https://github.com/eidheim/Simple-Web-Server

**Comment by eidheim** [comment]
Ah nvm, its in client_http.hpp, my bad. Will have a look.

**Comment by psy2013GitHub** [comment]
can you please fix it now, i can't even sleep well for this problem ;(....

**Comment by psy2013GitHub** [comment]
i'm quite new to c++ network programming...

**Comment by eidheim** [comment]
The problem is that you are sending wrong Content-Length, but fixing the exception now so that client_http.hpp handles this anyway.

**Comment by psy2013GitHub** [comment]
thanks for your time and patience, a happy talk.
