### ISSUE TITLE
CMake fails due to missing libboost_coroutine on CentOS 7

### ISSUE THREAD

**Issue by craigminihan** [eidheim/Simple-Web-Server#4]
CentOS 7 ships with Boost 1.53 which doesn't seem to contain libboost_coroutine. The headers are present but there is no lib. I assume this was added between 1.53 and 1.55.

The boost version check in CMakeLists.txt is 1.41 - I guess this should be updated to 1.55 to give a better user warning.

**Comment by eidheim** [comment]
Coroutine should be added in Boost version 1.53: http://www.boost.org/users/history/, but I will let CMakeLists.txt search for version 1.55 until I can confirm an earlier working Boost version.
