### ISSUE TITLE
Multiple Get requests on the same connection can fail because too many bytes are read

### ISSUE THREAD

**Issue by Halt001** [eidheim/Simple-Web-Server#40]
Hi,

I've been studying and testing this Simple Web Server and I found that if you send two requests, that have no body, over the same socket then bytes could be read (in the async_read_until(... "\r\n") that belong to the second request. 

You even mention in the comment that Boost could do this. The solution you mention only works if there is a body after the first request. If there isn't the bytes will eventually be lost when the first request instance containing the streambuf is destructed. For the second request on the same connection a new streambuf is used so previously read bytes beyond the first request are lost forever.

This is what I sent over the connection in one go: "GET /match/123 HTTP/1.1\r\n\r\nGET /match/456 HTTP/1.1\r\n\r\n" and what I saw happening was that the first 5 bytes of the second GET were also read from the socket and as a result they were missing when processing the second request.

Cheers,

Tim

**Comment by eidheim** [comment]
Thank you, I'll fix this Tomorrow.

**Comment by eidheim** [comment]
I'm having trouble deciding if I should add a fix for this or not: A HTTP client should wait for a response after the first GET, and if that is done, the issue described above will not happen, if I'm not mistaken.

**Comment by Halt001** [comment]
I guess you are right. HTTP 2.0 allows it but HTTP 1.1 doesn't. I used a mock test socket to cause this behaviour but it would probably be impossible to trigger with a real HTTP 1.1 client.
