### ISSUE TITLE
TCP packet handling on Linux behavior differs from OSX

### ISSUE THREAD

**Issue by SumolX** [eidheim/Simple-Web-Server#41]
When I stream mjpeg data on OSX it is working as expected with the tcp nodelay option being set.  Capturing the raw data via wireshark I can clearly see the tcp packets are more or less the size of the specified MTU (~1500 bytes) and the web client plays back the images properly with the expected framerate.

Now running my application on Linux the mjpeg stream data seems to combining multiple http messages together,  I am seeing tcp packets with a size more or less comparable to 65535 bytes.  I've tried enabling the TCP_CORK option via acquiring the native handle but i'm not seeing a difference in packet sizes on linux.  I would say it's almost like boost or the http server is holding back until the tcp buffer is full.

Any thoughts?

**Comment by eidheim** [comment]
The internal workings of boost asio might differ from OS to OS, and I have not investigated this, sorry. However, is not WebSocket (through for instance Simple-WebSocket-Server) better to use for streaming data?
