### ISSUE TITLE
Reinstate async_flush please.

### ISSUE THREAD

**Issue by SumolX** [eidheim/Simple-Web-Server#42]
I've come across an issue where I'm streaming data to two clients and I'm having async_writes interleaving between both clients and when this occurs the async_write hangs.  I believe you had previously solved this problem with your async_flush method (removed around Sept. 2015).

This link provides a better idea of what I'm experiencing:

http://stackoverflow.com/questions/7754695/boost-asio-async-write-how-to-not-interleaving-async-write-calls

EDIT

I ran a quick test with the version that still supported async_flush and with a quick hack of making those methods public, it worked perfectly as expected.

**Comment by eidheim** [comment]
The solution in the stackoverflow should not be needed for Simple-Web-Server, however, something similar is implemented in Simple-WebSocket-Server. 

How many threads are you using in the thread pool? Also make sure you use the response.flush() as shown in the default_resource example when transferring large amounts of data.

**Comment by SumolX** [comment]
The thread pool is set to 4.

Here is a snippet of my code, mind it is still a work in progress...

When new data has been acquired via the publisher/subscriber method
"Cameras::Update()", the stream is sent to a client and this works
perfectly for a single client.  When a second client is introduced, the
first iteration through _sessions is processed, but the moment the second
iteration calls response.flush() which in turn calls async_write, the
processing hangs and after some researching it seems I can not call an
async_write from an alternate response until the first async_write has
completed processing.

Now do keep in mind that  Cameras::Update() is being issued from an
alternate thread where the data is genrated.

void Cameras::Get(Response& response, Request request)
{
    KVP pairs;
    U32 stream_id = 0xFFFFFFFF;

    if (URLParameters(request->path, pairs))
    {
        /**
         *  Acquire stream id
         */
        auto id = pairs.find(property::Id);

        if (id != pairs.end())
        {
            stream_id = cast::ToU32(id->second);

            /**
             *  Acquire action
             */
            auto action = pairs.find(property::Action);

            if (action != pairs.end())
            {
                /**
                 *  Execute action: 'PLAY'
                 */
                if (value::Play == action->second)
                {
                    if (_sessions.size() < standard::ActiveSessions)
                    {
                        _sessions.emplace_back(response, stream_id);

                        if (InitiateStream(response))
                        {
                            /**
                             * Remain in this loop until session ends
                             */
                            Play(_sessions.back());
                        }

                        for (auto i = _sessions.begin(); i !=
_sessions.end(); ++i)
                        {
                            if (stream_id != 0xFFFFFFFF &&
                                stream_id == i->StreamId())
                            {
                                _sessions.erase(i);

                                break;
                            }
                        }
                    }
                    else
                    {
                        try
                        {
                            SendNACK(503, "Unable to reserve a video
stream, try again later.", response);
                        }
                        catch (const std::exception& e)
                        {
                            // TODO:  Log failure to respond to client.
                        }
                    }
                }

                /**
                 *  Execute action: 'STOP'
                 */
                if (value::Stop == action->second)
                {
                    if (!_sessions.empty())
                    {
                        for (auto& session : _sessions)
                        {
                            if (stream_id != 0xFFFFFFFF &&
                                stream_id == session.StreamId())
                            {
                                Stop(session);
                            }
                        }
                    }
                }
            }
        }
    }
}

bool Cameras::InitiateStream(Response& response)
{
    std::string error;

    try
    {
        /**
         *  Notify client we are going to stream a live video feed.
         */
        response << "HTTP/1.1 200 OK\r\n"
                    "Content-Type:
multipart/x-mixed-replace;boundary=stream\r\n"
                    "\r\n"
                    "--stream\r\n";

        response.flush();
    }
    catch (const std::exception& e)
    {
        error =
            "Failed to initiate video stream <" +
            std::string(e.what()) +
            ">";

        // TODO:  Log failure to respond to client.
    }

    return error.empty();
}

void Cameras::Play(Session& session)
{
    if (_cameras.get())
    {
        _cameras->Subscribe(this);
    }

    session.Play();

    while (session.Streaming())
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }

    if (_cameras.get())
    {
        _cameras->Unsubscribe(this);
    }

    try
    {
        Response& response = session.Response();

        /**
         *  Notify client we have ended the stream.
         */
        response << "HTTP/1.1 200 OK\r\n\r\n";

        response.flush();
    }
    catch (const std::exception& e)
    {
        // TODO:  Log failure to send response
    }
}

void Cameras::Stop(Session& session)
{
    session.Stop();
}

void Cameras::Update(const Publisher& publisher, const TLVS& tlvs)
{
    for (auto& session : _sessions)
    {
        if (session.Streaming())
        {
            U32 stream_id = 0xFFFFFFFF;

            try
            {
                for (auto& tlv : tlvs)
                {
                    switch (tlv.Tag())
                    {
                        case hdw::cameras::tlv::StreamId:
                        {
                            if (tlv.Length())
                            {
                                tlv >> stream_id;
                            }

                            break;
                        }
                        case hdw::cameras::tlv::StreamData:
                        {
                            if (tlv.Length() && stream_id ==
session.StreamId())
                            {
                                Response& response = session.Response();

                                printf("ip: %s, pt: %d\n",
response.remote_ip().c_str(), response.remote_port());

                                response << "Content-Type: image/jpeg\r\n"
                                            "Content-Length: " <<
tlv.Length() << "\r\n"
                                            "\r\n";

                                response.write
                                (
                                    (const char*)tlv.Value().data(),
                                    tlv.Length()
                                );

                                response << "\r\n--stream\r\n";

                                response.flush();

                                /**
                                 *  Reset stream index
                                 */
                                stream_id = 0xFFFFFFFF;
                            }

                            break;
                        }
                    }
                }
            }
            catch (const std::exception& e)
            {
                /**
                 *  Client has ended the session.
                 */
                session.Stop();
            }
        }
    }
}

**Comment by eidheim** [comment]
Simple-Web-Server is not made to call response.flush() asynchronously, that is one resource handle only its anonymous function's response, not others. I would suggest you use Simple-WebSocket-Server instead. See here for a simple streaming example I made for a classroom that does not have video cannon and screen: https://github.com/eidheim/desktop-stream

**Comment by eidheim** [comment]
Regarding the async_flush I added, it is quite unsafe to use with respect to programming, and one could quickly make bad choices like using async_flush in a large for loop and thus use up available memory. Also, HTTP is not meant for making streaming solutions, while instead, the now widely available WebSocket protocol is a better choice.

**Comment by SumolX** [comment]
Thank you for clarifying the intent of both services and providing an example.  I will update my software to reflect the design patterns you have identified.
