### ISSUE TITLE
Correctly handle  bind: Address already in use

### ISSUE THREAD

**Issue by pavel-odintsov** [eidheim/Simple-Web-Server#43]
Hello!

Thanks for your clean and nice code!

But I've got this error about already running another instance:
```bash
Start server
Wait for server shutdown
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
Aborted
```

From my point of view it's pretty useful thing to handle this case explicitly.

**Comment by eidheim** [comment]
Does Config::reuse_address solve this (`server.config.reuse_address=true;` before start)? Also have a look at #26, where we discussed this.

**Comment by eidheim** [comment]
When looking closer I saw that reuse_address is true by default. My bad, but could you explain more closely how you would like to handle the exception?

**Comment by pavel-odintsov** [comment]
Hello!

I just need some human friendly error in this case instead of program exited by system_thrown.

**Comment by eidheim** [comment]
If I'm not misunderstanding, I would place the `server.start()` in a try block, and handle the error in its catch block.

**Comment by pavel-odintsov** [comment]
Right! That's what I'm looking for. I think it's nice to have all cases handled in your server.

**Comment by eidheim** [comment]
In my opinion, the user of the library should handle such exceptions appropriate to the application. I do not think I will change that, sorry.

**Comment by pavel-odintsov** [comment]
So I could agree with your point of view. Otherwise library could be bloated by useless code. Thanks! Will do it in my code.
