### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by eidheim** [eidheim/Simple-Web-Server#46]
This library was created mainly as a really simple way to create REST resources in C++, at a time when there were no good alternatives available. However, now, I'd like to make this library fully asynchronous, and thus more flexible regarding thread strategies. It would then be more like https://github.com/eidheim/Simple-WebSocket-Server, which I am more happy with. Of course, the default_resource example would be slightly more complex, and would have to rely on recursive calls (much like the express library for NodeJS). The resource signature would also become:
```c++
[](shared_ptr<HttpServer::Response> response, shared_ptr<HttpServer::Request> request)
```
instead of the current:
```c++
[](HttpServer::Response& response, shared_ptr<HttpServer::Request> request)
```
One other advantage is a slight speed increase due to removing `boost::asio::spawn` and `boost::asio::yield_context`. Feel free to post opinions on this.

**Comment by eidheim** [comment]
@drpatrik and @jeffreyscottgraham Your thoughts on this would be very welcome.

**Comment by drpatrik** [comment]
I do not think that the new resource signature introduces any complexity. If that is the only drawback with a 2.0 I am all for it :-)

We have not benchmarked your library yet, but my gut feeling is that its fast enough for our needs.

**Comment by SamuelMarks** [comment]
@drpatrik Actually on that note would likely be useful to make some benchmarks <2 and >2 to measure the performance impact an asynchronous paradigm shift would make.

**Comment by eidheim** [comment]
See the v2 branch. I noticed a speed increase especially when running one thread only. I'll add another example, a heavy processing example, then most likely merge it to master soon.
