### ISSUE TITLE
How can I get to the parameters?

### ISSUE THREAD

**Issue by Reloner** [eidheim/Simple-Web-Server#47]
my code：
.....
server.resource["^/login?|signature=([0-9]+)|timestamp=([0-9]+)|nonce=([0-9]+)|echostr=([0-9]+)"]["GET"] = [](HttpsServer::Response& response, shared_ptr<HttpsServer::Request> request) {
        .......
    };
.....

my request:
http://127.0.0.1/login?signature=112&timestamp=12312&nonce=22&echostr=11

but I never get the parameters

**Comment by eidheim** [comment]
See https://github.com/eidheim/Simple-Web-Server/blob/master/http_examples.cpp#L79. You get the parameters using request->path_match. [1] corresponds to signature, [2] timestamp and so on.

**Comment by Reloner** [comment]
@eidheim ，without effect，
When a regular expression is judged, it does not hold, so it can not be used to obtain the parameters in this method.

**Comment by eidheim** [comment]
I got it working with the following regex (only two parameters):
`server.resource["^/login\\?signature=([0-9]+)&timestamp=([0-9]+)$"]["GET"]=`
There are some alternatives you could do:
* require the parameters to come in a specific order, although this is not according to HTTP standard
* use a separate GET parameter parser, or create on yourself. For instance use the following resource then:
`server.resource["^/login\\?(.*)$"]["GET"]=` and parse `request->path_match[1]. 
* set the arguments to the HTTP header instead

**Comment by drewcoo** [comment]
@Reloner - you can capture everything from just after the question mark to the end of the string. Then you can split that (presumably into a vector) on ampersands. Then you can split each of those (presumably into a map) on equal signs. You now have key-value pairs and don't need to worry about ordering or even number of pairs in the regular expression.

I don't think this is a bug with this library.

(Nice job, @eidheim.! I was just checking out your open issues to decide whether to use your library and it looks pretty clean/safe.)

**Comment by eidheim** [comment]
Closing this since we have added `Server::Request::parse_query_string()`
