### ISSUE TITLE
can't make when trying to connect mysql

### ISSUE THREAD

**Issue by peldhose** [eidheim/Simple-Web-Server#48]
when I am trying to connect to db through "mysql.h", I am getting error like 

    http_examples.cpp:(.text+0x2967): undefined reference to `mysql_init'
    http_examples.cpp:(.text+0x2990): undefined reference to `mysql_real_connect'
    http_examples.cpp:(.text+0x2bc6): undefined reference to `mysql_free_result'
    http_examples.cpp:(.text+0x2bd2): undefined reference to `mysql_close'
    http_examples.cpp:(.text+0x2d03): undefined reference to `mysql_error'.
How can i fix it?

**Comment by eidheim** [comment]
You probably need to link to the mysql library. I'm not sure, but maybe add `-lmysqlclient` to the CXX flags at least to get it working. There might be a FindMySQL.cmake out there somewhere too, which might be a better idea to use.
