### ISSUE TITLE
Fail to create shared pointer from HttpServer

### ISSUE THREAD

**Issue by piction** [eidheim/Simple-Web-Server#49]
```
typedef SimpleWeb::Server<SimpleWeb::HTTP> HttpServer; 
...
HttpServer server(8080,1);  
std::shared_ptr<HttpServer> pServer = std::make_shared<HttpServer>(server);
xxxx.RegisterApis(pServer);
yyyy.RegisterApis(pServer);
```

When I try this, it results in multiple errors ...

- error : boost::asio::io_service::io_service(const boost::asio::io_service&)' is implicitly deleted because the default definition would be ill-formed:

- error: 'boost::asio::detail::noncopyable::noncopyable(const boost::asio::detail::noncopyable&)' is private
   noncopyable(const noncopyable&);

- error: use of deleted function 'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>::basic_socket_acceptor(const boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>&)'
     class ServerBase

Are there solutions to solve this problems ?
I would like to pass the server pointer to a function that registers resources in the std_unordered_map recource.

Thanks in advance

**Comment by eidheim** [comment]
Do this instead:
```c++
auto server=make_shared<HttpServer>(8080, 4);
```
