### ISSUE TITLE
When starting Two server instances on diferent ports (even different interfaces) on same program just the second one works.

### ISSUE THREAD

**Issue by NicolasPena** [eidheim/Simple-Web-Server#52]
When starting two server instances on different ports (even different interfaces) on same program just the second one works. It looks like the instantiation of two servers on a single program, running in deferent treads and not sharing anything, is not supported as, some how the second one blocks the first one.
If you need me to provide more information i will be a pleasure!
Very nice library by the way!

**Comment by NicolasPena** [comment]
I forgot to mention that I am using the latest version.

**Comment by eidheim** [comment]
Strange, I've been using Simple-Web-Server together with Simple-WebSocket-Server many times. What OS are you on?

**Comment by NicolasPena** [comment]
Ubuntu 16.04.
I have been investigating and it look like is the resources vector that is
being overwritten by the new instance.

**Comment by eidheim** [comment]
You sure you have two different server objects? There are no statics:)

**Comment by NicolasPena** [comment]
Yes.. search for the word static was the first thing I did ;-). They are
two instances created from different threads.

**Comment by eidheim** [comment]
Would you mind creating a minimal test case where this fails, and I'll have a look at it when I have time.

**Comment by NicolasPena** [comment]
Yes, I will do that. Thanks!

**Comment by NicolasPena** [comment]
My bad... I was to quick to blame your library... sorry!
It was a problem with identical namespaces (bug on my side) in different
places that where just manifesting when instancing two servers...

Sorry for making you loose your time and thanks for your help!!

Best regards,

              Nicolas.

**Comment by eidheim** [comment]
No worries, glad it got resolved:)
