### ISSUE TITLE
Maximum threads for Http Server

### ISSUE THREAD

**Issue by rragu** [eidheim/Simple-Web-Server#55]
Hi,

How many maximum threads can be created for Http Server. As it said 4 over in the code.

`HttpServer server(8002, 4);`

Also i want to know what is the maximum length of response data.

Thanks in advance.

**Comment by eidheim** [comment]
Sorry for the late reply, but there is no max threads or maximum length of response data other that OS restrictions and memory size. Use flush as shown in the default_resource example if you are sending really large responses though.
