### ISSUE TITLE
Recommended lifetime of HttpClient? (documentation request)

### ISSUE THREAD

**Issue by MatrixManAtYrService** [eidheim/Simple-Web-Server#57]
First of all, thanks for making this.  I wasted much time with a different library first, and life got much better when I switched to yours.

I have an app with a server that listens to several endpoints.  One of them is `/clocktick`.  In order to test this app, I made a tester which assigns to each endpoint a key on the keyboard.  So, when I press `enter` the tester app sends an empty POST request at '/clocktick'.

I have noticed that if I hit `enter` quickly (say, once per second) the requests make it through.  But if I stop and wait for six seconds, and then hit it, the request will get dropped and I will get an exception when `client.request` is called (read_until: An established connection was aborted by the software on your host machine).  I noticed a timeout in your README.md of 5 seconds--it seems like HttpClient holds a connection open for some duration, and if I catch it while that connection is closing I have the problem.  If I wait longer, there is a delay for the first request--perhaps it is reopening a connection?

I create an instance of HttpClient when my program starts up and pass pointers to interested classes so they can each use it (i.e. dependency injection).  I'm thinking maybe it would be better if the client was created right before it was needed, and then disposed of until next use--that way there would be no risk of catching it in the 5-seconds-later window where it doesn't work.  Would that make sense?

I plan to investigate using Simple-WebSocket-Server to propagate clockticks instead--but I do still plan to use Simple-Web-Server for other resources and it would give me a nice happy feeling if I understood a bit more about what was happening regarding those timeouts.  This issue is to request that you expand the readme a bit so that users of your library are better prepared to use it in a way that makes sense.

Also, if this is basic knowledge about HTTP that a typical user should already know, then I apologize and thank you for your time.

**Comment by eidheim** [comment]
The HttpClient is very basic, and in this case I would wait with constructing HttpClient until I had the data ready to send. The reason why there is a separate constructor and request method is that you can send several request in the same connection. If it is a good idea to establish the connection already at the constructor is another discussion, but in C++, having extra functionality in the construction of an object is not uncommon. std::thread is a good example of this, and you are free to delay the construction of the object in many ways, for instance using std::unique_ptr instead to store the client instance. 

You can change the request timeout in the HttpServer constructor, default is 5 seconds if I remember correctly, and 30 seconds on content. I should maybe document a bit more, you are quite right there! I'll have a look at this library during the summer, and most likely implement Simple-Web-Server 2.0 that is fully asynchronous (see the enhancement issue, and feel free to add your input).

Yes, I would suggest using Simple-WebSocket-Server, which is already fully asynchronous, for full-duplex communications, like clockticks if I understand the application correctly, to and from a web client. If you want to write the server in C++ that is:) My initial thought of this library was streaming and more heavy processing tasks, however, which it should be able to handle. 

Sorry for the late response!
