### ISSUE TITLE
How do I set the content-type to application/json while using the client examples?

### ISSUE THREAD

**Issue by ujjwalsubedi** [eidheim/Simple-Web-Server#58]
I'm trying to communicate with the docker remote api using the POST method. But I'm getting this error:
**Content-Type specified () must be 'application/json'**

Is it possible to set the content-type of the body using this library?

**Comment by eidheim** [comment]
You can add a map with header parameters when you call the request method. See https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L51.

**Comment by ujjwalsubedi** [comment]
thanks for the info. It worked
