### ISSUE TITLE
How do I establish an HTTPS connection with the HttpsClient verify_certificate set to true? 

### ISSUE THREAD

**Issue by bhanushrestha** [eidheim/Simple-Web-Server#66]
While there is the https_examples.cpp that shows how to create a HTTPS server properly, the HTTPS client defined in that particular example sets verify_certificate to false. Could you explain what the other parameters mean? I created a new SSL certificiate with a key but the final parameter asks for a verify_file; what does it refer to? A few helpful comments in the https portion of your system would really be helpful. Thank you.

Also, I got this error when i tried to pass the csr file created by openssl as the final parameter:: 
```
terminate called after throwing an instance of 'std::invalid_argument'
 what():  stoul
```

**Comment by eidheim** [comment]
OpenSSL should now find the certificate files correctly, the the example below should work. The other parameters are most likely not needed in your case. 

```c++
#include "client_https.hpp"
#include <iostream>

using namespace std;

typedef SimpleWeb::Client<SimpleWeb::HTTPS> HttpsClient;

int main() {
    HttpsClient client("github.com");
    auto r1=client.request("GET", "/");
    cout << r1->content.rdbuf() << endl;
}
```

**Comment by bhanushrestha** [comment]
Thank you for the quick action but i still get the following error when i run the client::

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  handshake: certificate verify failed
```

I have the server.crt, server.csr, server.key files all in the root of your project itself.

The certificate was created using http://www.akadia.com/services/ssh_test_certificate.html as you suggested in your ReadMe file.

Also an added question, how do you define where the program looks for these certificates for the HTTPS connection.

**Comment by eidheim** [comment]
The simple version is: If your certification files are self-signed, you need to turn off verification when using the client to connect. However, if your server certificate is signed by a trusted certificate authority, you can connect with verification. 

Certificates are located on your computer at a standard location. Depending on your OS, you can add and trust certificates there if I'm not mistaken.

**Comment by bhanushrestha** [comment]
@eidheim Sorry to be bothering you againg but I am trying to use self signed certificate in both client and server side so that both the client knows that this server is who it is claiming to be and the client should also in the same way be able to verify that it is this particular client to the server so that both can acknowledge that the communication  between them is genuinely secure and to the right program.

How can we manage it with your library?

I cannot figure out how the verify_certificate=true work either. Sorry I just want to create a secure HTTPS communication with certificates shared at both sides. It should be possible with your library since you use OpenSSL. But how do i do that?

**Comment by eidheim** [comment]
I am not actually sure how to do this with a self signed certificate. Normally one would skip verify_certificate with a self-signed one, or one that is not signed by a trusted Certificate Authority. However, I am sure one can add a self-signed certificate to your operating system somehow, and say that you trust your own certificate, that is, in this case, you are your Certificate Authority for your computer, in a way.

**Comment by bhanushrestha** [comment]
And how about the client verification portion of the HTTPS communication, how can we exchange a certificate from client side to prove the client's identity for the server?

**Comment by eidheim** [comment]
I am not sure, but feel free to play around with the library to make this possible. There are probably some OpenSSL options on the Boost.Asio side that does this. I would read up on OpenSSL and Boost.Asio first though. Let me know what you learn, I would love to know more about this as well:)

**Comment by isaacsmead** [comment]
Client side cert works for me.  The calls in the API seem to pass directly through the asio::ssl to openssl.  On server I pass my CA chain as the final arg.  If you're self signed i'm not sure, but passing your cert should work.  On client side you can pass your cert, key, and verify_file in the constructor the same way as server.  Be aware that passing true for verify_certificate will cause it to throw error for things like URL not matching your cert.  You can set this to false and still pass the client cert/key as 3rd and 4th argument.
