### ISSUE TITLE
Localhost, Mozilla Firefox

### ISSUE THREAD

**Issue by cocotte6** [eidheim/Simple-Web-Server#70]
Hello, 

I am using this web server. Localhost is very slow (5 seconds to generate the HTML page) on the browser MozillaFirefox (even for a simple 'hello world'). I worked on Linux. 

I have tried with Opera and Chrome, it is very fast. 
I tried connecting to localhost using Apache on MozillaFirefox , no problem.

Do you know what can cause this problem ? 

Thanks for your help !

**Comment by eidheim** [comment]
Might be some http headers that Firefox is looking for? You could try add some more typical headers to the http_examples.cpp. I just tried newest firefox by the way, but on OS X, and did not see any problems.

You should also double check that the content-length is set correctly.

**Comment by eidheim** [comment]
It might be that the default_resource example sent an empty response. I fixed this in https://github.com/eidheim/Simple-Web-Server/commit/4efd3bf83c4f53ba6bd055d5de674b17550ee650 just now.

**Comment by Allov** [comment]
I don't know if it's related, but the way I built the response I didn't have breaklines (\r\n) and chrome, in my case, was taking 5s to resolve the headers.

Here's the CORRECT way to do it:

```cpp
	HttpServer server(5555, 1);

	server.resource["^/$"]["GET"] = [](std::shared_ptr<HttpServer::Response> response, std::shared_ptr<HttpServer::Request> request) {
		TTCore::String content = "Hello world";
		*response << "HTTP/1.1 200 OK\r\n"
				  << "Content-Length: " << content.length() << "\r\n\r\n" << content;
	};

	std::thread server_thread([&server](){
		//Start server
		server.start();
	});
```

**Comment by Lewiscowles1986** [comment]
confirmed http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4 it is supposed to use CRLF
