### ISSUE TITLE
can't get index page to display

### ISSUE THREAD

**Issue by leogi22** [eidheim/Simple-Web-Server#71]
I am running the https_examples and the https server comes up, starts with the self signing certificate and key file, and the https clients examples from within the c++ file connect and the server couts the data correctly on the output. However, nothing happens when pointing the browser to https://localhost:8080, either with firefox nor ie. First time, I had the certificate warning (because of the self signing situation), I then added an exception, and now no longer a warning but simply a give up message.
On the server side, I get the boost "size_t win_iocp_io_service::do_one(bool block, boost::system::error_code& ec)" function is called and goes into op->complete, however nothing seems to be sent to the browser in response to its GETS request.

**Comment by eidheim** [comment]
It might be that the default_resource example sent an empty response. I fixed this in https://github.com/eidheim/Simple-Web-Server/commit/4efd3bf83c4f53ba6bd055d5de674b17550ee650 just now.

**Comment by leogi22** [comment]
let me try. 
However, I don't think my cout in there ever get called, but I'll try with your new handle anyways

**Comment by leogi22** [comment]
ok, indeed, getting a path not found error message, as expected. Thanks!
