### ISSUE TITLE
how to enable keep_alive in the HTTP(S) client

### ISSUE THREAD

**Issue by CheyenneForbes** [eidheim/Simple-Web-Server#73]
I would like to keep the connection open to make a Prepare request (POST) then an Excexute request (POST) to my database server (with the same connection). With the ability to close the connection by calling something like close() after I sent both requests with the connection.

in python (request module) you open the connection then make the requests then call connection.close() to close the connection to the server

**Comment by eidheim** [comment]
See for instance the header parameters at https://github.com/eidheim/Simple-Web-Server/blob/master/client_http.hpp#L51. If you are talking to a HTTP 1.0 server you might keep alive the server with the `Connection: keep-alive` header parameter (https://en.wikipedia.org/wiki/HTTP_persistent_connection). 

To close the connection you add `Connection: close` to the header. Or you can destroy the `Client` object.

**Comment by CheyenneForbes** [comment]
What about a RPC server that automatically keeps the connection alive?

**Comment by eidheim** [comment]
If the server does not support `Connection: close` I would destroy the client object by for instance moving out of scope.

**Comment by CheyenneForbes** [comment]
Thank you
