### ISSUE TITLE
CMake Windows Support

### ISSUE THREAD

**Issue by cyberhooper** [eidheim/Simple-Web-Server#74]
Does this project support CMake on windows? I am having issues generating a project for Visual Studio 2015.

**Comment by eidheim** [comment]
CMake is now the typical way to create platform independent builds, but on some occasions platform specific fixes has to be added to the cmake files. I have never tested it on Visual Studio, and never will, but if there are issues, and you find a solution for it, feel free to create a pull request. But I would strongly advice against running server services on a Windows OS.

**Comment by cyberhooper** [comment]
Thanks for the info. I was able to get it to work with out CMake. I will post code soon. Just curios why would recommend  not running  server services on windows?

**Comment by eidheim** [comment]
There are many reason why not to use Windows as a server, but the main one is lack of a well tested package system. How many are using the OpenSSL and Boost version you are using, compared to how many are using for instance Debian stable's OpenSSL and Boost packages. See also https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Public_servers_on_the_Internet where 98.3% of the top 1 million web servers on the internet are using Posix systems. Windows is the non-Posix system that we need to port packages to, and these ports are not necessarily well tested, especially not the versions you, or other Windows users, might be using.

**Comment by nunojpg** [comment]
@eidheim Kudos for reasoning why not to do it. I would like to possibly clarificate that this is more important for internet facing services. As a library to provide rest endpoints (imagine docker API) as part of a Windows application, not internet routable, I don't think there is any strong reason against.

**Comment by Socapex** [comment]
I'd like to pitch in as well. I need Windows support not to run the release build server (that's Linux of course), but for development purposes + collaboration with my colleagues.

Note that I've also had to do some tooling daemon that requires an http server for inter-process communications (we don't control the format), and that was on Windows as well. This was not web facing.

Anyhow, as I've proposed in another issue I'd like to send a PR for Windows support. Simple-Web-Server looks awesome and it's a shame it doesn't run on Windows.

**Comment by MatrixManAtYrService** [comment]
The project I'm using this for targets Linux, but there's a windows-only simulator that we use, so it has been necessary to maintain cross-platform compatibility.  It's been a year and a half of pretty much daily development and I have yet to come across a problem regarding Simple-Web-Server (or Simple-WebSocket-Server) that seems to be windows-related.

We use CMake to generate our visual studio solution and as long as you link to OpenSSL (which we build  separately) everything just works.

**Comment by SethHamilton** [comment]
For windows I simply added it to my `include_directories` like this:
```
include_directories(src lib vendor/lz4/lib vendor/asio/asio/include vendor/simple-web-server)
```
in my `set` statement I add the `.hpp` files, like this:

```
set(SOURCE_FILES
        vendor/lz4/lib/lz4.c
        vendor/lz4/lib/lz4.h
        vendor/lz4/lib/xxhash.c
        vendor/lz4/lib/xxhash.h
	vendor/asio/asio/include/asio.hpp
	vendor/simple-web-server/server_http.hpp
	vendor/simple-web-server/client_http.hpp
        .... and so on
```
I used the stand-alone ASIO, created a sub-repo in my main repo under the `vendor` folder. The git repo for stand-alone ASIO is here: https://github.com/chriskohlhoff/asio/

This worked.

**Comment by eidheim** [comment]
This issue is hopefully fixed in: https://github.com/eidheim/Simple-Web-Server/commit/5a7c021dab6de484590a45701e8eab29b1a7b718
