### ISSUE TITLE
cout is not working in lambda function of a route

### ISSUE THREAD

**Issue by johnlowvale** [eidheim/Simple-Web-Server#81]
the code inside a handler works as usual, except 'cout', for example:

```
server.resource["^/$"]["GET"] = [](................){
  cout << "abc";
};
```

it doesn't print out anything

```
void handle_get_root(.........................){
  cout << "xyz";
}

server.resource["^/$"]["GET"] = handle_get_root;
```

doesn't print out 'xyz' too

**Comment by johnlowvale** [comment]
tks god, i found the answer:
http://stackoverflow.com/questions/14858262/stdcout-wont-print

i need to call cout.flush()

but i still don't know why i have to call 'flush'.

most of the time nobody needs to call 'flush'

**Comment by eidheim** [comment]
There are no guarantees that a flush is called when you use `std::cout`, unless using `std::endl`, `std::flush`, or when a program exits. In the case above, I would simply write `cout << "abs" << endl;` when using `std::cout` for testing purposes.

**Comment by johnlowvale** [comment]
ah yeah, endl works
