### ISSUE TITLE
HTTP(s)-Server crashes in start() if used with a "stopped" io_service.

### ISSUE THREAD

**Issue by lSoleyl** [eidheim/Simple-Web-Server#82]
Hi,

I came across this bug, when trying to run both Simple-Websocket-Server and Simple-Webserver through the same io_service. Following code should reproduce the error:

    auto io_service = std::make_shared<boost::asio::io_service>();
    
    HttpServer server(80, 0);
    server.io_service = io_service;
    server.start();

The reason seems to be the call to `io_service.reset()` (instead of `io_service->reset()`) in `start()`. https://github.com/eidheim/Simple-Web-Server/blob/master/server_http.hpp#L151

**Comment by eidheim** [comment]
Thank you for seeing this!
