### ISSUE TITLE
No way to interrupt a client request (app shutdown during long polling)

### ISSUE THREAD

**Issue by Skywalker13** [eidheim/Simple-Web-Server#86]
Hello,

I'm doing long polling with `client_https.hpp` but I'v a problem when the app is exiting. The long polling can be very long and I must interrupt. I think that it should be possible to close the socket in order to force to stop the request.

Or maybe there is already an other way?

**Comment by eidheim** [comment]
Sadly, it has proven difficult to implement timeouts with the synchronous asio operations previously. I think the solution is to move away from these operations and use asynchronous reads and writes instead. I'll try find some time to do this soon.

**Comment by Skywalker13** [comment]
OK, now I must detach the thread and then it's just killed by the OS when the main process is exiting. It's very ugly but if it's just a temporary workaround; I can live with it...

**Comment by eidheim** [comment]
You can now set timeouts on client requests using Client::config::timeout

**Comment by Skywalker13** [comment]
That's not really the fix for this issue. I need to stop the request at any time.

It's not tested but it should be possible with something like that, no?
```diff
diff --git a/client_http.hpp b/client_http.hpp
index a9b6344..2594f39 100644
--- a/client_http.hpp
+++ b/client_http.hpp
@@ -147,6 +147,12 @@ namespace SimpleWeb {

             return request_read();
         }
+
+        void abort() {
+            boost::system::error_code ec;
+            socket->lowest_layer().shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
+            socket->lowest_layer().close();
+        }

     protected:
         boost::asio::io_service io_service;
@@ -181,11 +187,8 @@ namespace SimpleWeb {
             auto timer=std::make_shared<boost::asio::deadline_timer>(io_service);
             timer->expires_from_now(boost::posix_time::seconds(config.timeout));
             timer->async_wait([this](const boost::system::error_code& ec) {
-                if(!ec) {
-                    boost::system::error_code ec;
-                    socket->lowest_layer().shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
-                    socket->lowest_layer().close();
-                }
+                if(!ec)
+                    abort();
             });
             return timer;
         }
```

**Comment by eidheim** [comment]
Yes, this is an option. Would maybe call it `close()` instead though, since that is what it basically does; closing the socket.

**Comment by eidheim** [comment]
Added the close (abort) method you suggested.

**Comment by Skywalker13** [comment]
Thank you very much

**Comment by eidheim** [comment]
I made the Client::close method in commit https://github.com/eidheim/Simple-Web-Server/commit/76bf8942fde3f2042091c8e69ea6388c7bad0c6d just now.

**Comment by Skywalker13** [comment]
OK; I was thinking that was thread-safe because no mutex was used in `timer->async_wait` in your previous code. Then it seems that even without the `close()` method, it was not thread-safe.

**Comment by eidheim** [comment]
The asio handlers are running in the same thread, so they are thread safe in the Client. The close method, however, introduced thread unsafe code.
