### ISSUE TITLE
client_https doesnt validate if the certificate match the server

### ISSUE THREAD

**Issue by sebt3** [eidheim/Simple-Web-Server#90]
Hi,

while Client&lt;HTTPS&gt; does check for the certificate validity, it doesnt verify that this host is actually allowed to use this certificate. So https://piratestuff.com could provide the certificate from https://www.google.com and get away nicely.

To implement this, you've to loop throw all the X509 common/general names and match the url name you're connecting to. It's a bit painfull to do, and I dont know if boost provide anything usefull for this.

I'm not actually requiering this for now. That's why this is an issue and not a pull request. I wanted to take a note and made sure you were aware of this problem

**Comment by eidheim** [comment]
Thank you again, but just so I understand this 100%: part of verifying a certificate is to check that the address is correct. Next, if one does reuse a certificate (let's say you have set up a wireless router with your own dns server someone is connecting to), one would need to someway find the corresponding private key for the public key that is in the certificate for exchanging the symmetric key. This way, reusing a certificate is not very useful (you would not be able to decrypt the symmetric key sent from the client), unless you have managed to steal the private key for the host the certificate is for. Or am I missing something?

**Comment by sebt3** [comment]
See it the other way around :
You're currently consuming some REST service, say https://api.somesite.com/something.json.
Any pirate able to take over the URL (DNS cache poisoning, any man in the middle attack...) could use *any* valid certificate (and matching private key) to over take the service.

In this situation, your browser would report the communication *unsecure* with the error : (net::ERR_CERT_COMMON_NAME_INVALID).
but the Client&lt;HTTPS&gt; would be glad to accept the data as the certificate is valid... even if not for this host.
To have your browser accept the certificate as valid the commonName of the certificate has to match the hostname in the url.

On a side note, I wrote a documentation on how to setup ssl certificate for my project : https://sebt3.github.io/watched/doc/secure_back/
You could use the last part to test the scenario I'm refering.

**Comment by eidheim** [comment]
I think you are right, and thank you again for the explanation and finding this critical issue. I'll read up on this a bit more, but at the moment I belive the following diff might solve the issue
```diff
diff --git a/client_https.hpp b/client_https.hpp
index bd67665..4cca119 100644
--- a/client_https.hpp
+++ b/client_https.hpp
@@ -16,6 +16,7 @@ namespace SimpleWeb {
                 ClientBase<HTTPS>::ClientBase(server_port_path, 443), context(boost::asio::ssl::context::tlsv12) {
             if(verify_certificate) {
                 context.set_verify_mode(boost::asio::ssl::verify_peer);
+                context.set_verify_callback(boost::asio::ssl::rfc2818_verification(host));
                 context.set_default_verify_paths();
             }
             else
```

Does it look ok to you?

**Comment by eidheim** [comment]
If the I set an incorrect host, the client throws the following exception: `boost::system::system_error: certificate verify failed`

**Comment by sebt3** [comment]
great ! Sound like it. Now if only this could be disabled :P

**Comment by eidheim** [comment]
Great, should be fixed in the above commit.

**Comment by sebt3** [comment]
Perfect, thanks a lot :)
