### ISSUE TITLE
async_connect doesn't timeout

### ISSUE THREAD

**Issue by aaalgo** [eidheim/Simple-Web-Server#91]
Client::request could return well beyond 30s even if config.timeout is set.   The issue has been discussed in the following two threads.  I think the first is more relevant.

http://stackoverflow.com/questions/32692195/set-timeout-for-boost-socket-connect
http://stackoverflow.com/questions/32692195/set-timeout-for-boost-socket-connect

**Comment by eidheim** [comment]
Thank you for noticing. It should be fixed in the above commit.

**Comment by aaalgo** [comment]
Works like a charm.  Thank you!
